/********************************************************************************
** Form generated from reading UI file 'hexui.ui'
**
** Created by: Qt User Interface Compiler version 5.13.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HEXUI_H
#define UI_HEXUI_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_HexUI
{
public:
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *pushButton;
    QPlainTextEdit *NumePlayer2_2;
    QLabel *CuloarePlayer1;
    QPlainTextEdit *NumePlayer1_2;
    QLabel *NumePlayer1;
    QLabel *NumePlayer2;
    QLabel *CuloarePlayer2;
    QComboBox *comboBox_P1;
    QComboBox *comboBox_P2;
    QLabel *MesajEroare;
    QWidget *page_2;
    QLabel *label;
    QPushButton *ButtonHex_0_8;
    QPushButton *ButtonHex_0_5;
    QPushButton *ButtonHex_0_4;
    QPushButton *ButtonHex_0_10;
    QPushButton *ButtonHex_0_6;
    QPushButton *ButtonHex_0_2;
    QPushButton *ButtonHex_0_0;
    QPushButton *ButtonHex_0_1;
    QPushButton *ButtonHex_0_7;
    QPushButton *ButtonHex_0_3;
    QPushButton *ButtonHex_0_9;
    QPushButton *ButtonHex_1_1;
    QPushButton *ButtonHex_1_0;
    QPushButton *ButtonHex_1_5;
    QPushButton *ButtonHex_1_7;
    QPushButton *ButtonHex_1_3;
    QPushButton *ButtonHex_1_8;
    QPushButton *ButtonHex_1_2;
    QPushButton *ButtonHex_1_6;
    QPushButton *ButtonHex_1_10;
    QPushButton *ButtonHex_1_4;
    QPushButton *ButtonHex_1_9;
    QPushButton *ButtonHex_3_10;
    QPushButton *ButtonHex_2_7;
    QPushButton *ButtonHex_3_5;
    QPushButton *ButtonHex_3_3;
    QPushButton *ButtonHex_2_9;
    QPushButton *ButtonHex_2_8;
    QPushButton *ButtonHex_3_7;
    QPushButton *ButtonHex_2_3;
    QPushButton *ButtonHex_3_0;
    QPushButton *ButtonHex_3_2;
    QPushButton *ButtonHex_3_4;
    QPushButton *ButtonHex_2_5;
    QPushButton *ButtonHex_2_1;
    QPushButton *ButtonHex_2_10;
    QPushButton *ButtonHex_2_2;
    QPushButton *ButtonHex_3_8;
    QPushButton *ButtonHex_3_9;
    QPushButton *ButtonHex_3_1;
    QPushButton *ButtonHex_2_0;
    QPushButton *ButtonHex_2_4;
    QPushButton *ButtonHex_3_6;
    QPushButton *ButtonHex_2_6;
    QPushButton *ButtonHex_4_0;
    QPushButton *ButtonHex_7_10;
    QPushButton *ButtonHex_7_4;
    QPushButton *ButtonHex_4_4;
    QPushButton *ButtonHex_5_6;
    QPushButton *ButtonHex_6_8;
    QPushButton *ButtonHex_6_10;
    QPushButton *ButtonHex_7_5;
    QPushButton *ButtonHex_4_7;
    QPushButton *ButtonHex_6_6;
    QPushButton *ButtonHex_5_2;
    QPushButton *ButtonHex_4_1;
    QPushButton *ButtonHex_4_5;
    QPushButton *ButtonHex_4_10;
    QPushButton *ButtonHex_6_3;
    QPushButton *ButtonHex_4_6;
    QPushButton *ButtonHex_5_5;
    QPushButton *ButtonHex_7_6;
    QPushButton *ButtonHex_5_7;
    QPushButton *ButtonHex_4_2;
    QPushButton *ButtonHex_5_1;
    QPushButton *ButtonHex_6_4;
    QPushButton *ButtonHex_6_2;
    QPushButton *ButtonHex_5_9;
    QPushButton *ButtonHex_4_9;
    QPushButton *ButtonHex_7_1;
    QPushButton *ButtonHex_4_3;
    QPushButton *ButtonHex_7_2;
    QPushButton *ButtonHex_7_8;
    QPushButton *ButtonHex_7_7;
    QPushButton *ButtonHex_4_8;
    QPushButton *ButtonHex_5_0;
    QPushButton *ButtonHex_6_1;
    QPushButton *ButtonHex_5_4;
    QPushButton *ButtonHex_5_3;
    QPushButton *ButtonHex_5_10;
    QPushButton *ButtonHex_6_9;
    QPushButton *ButtonHex_6_7;
    QPushButton *ButtonHex_5_8;
    QPushButton *ButtonHex_7_0;
    QPushButton *ButtonHex_6_5;
    QPushButton *ButtonHex_7_3;
    QPushButton *ButtonHex_6_0;
    QPushButton *ButtonHex_7_9;
    QPushButton *ButtonHex_10_4;
    QPushButton *ButtonHex_8_8;
    QPushButton *ButtonHex_10_6;
    QPushButton *ButtonHex_8_0;
    QPushButton *ButtonHex_8_9;
    QPushButton *ButtonHex_9_6;
    QPushButton *ButtonHex_9_9;
    QPushButton *ButtonHex_10_2;
    QPushButton *ButtonHex_10_0;
    QPushButton *ButtonHex_8_2;
    QPushButton *ButtonHex_9_7;
    QPushButton *ButtonHex_9_3;
    QPushButton *ButtonHex_9_10;
    QPushButton *ButtonHex_9_0;
    QPushButton *ButtonHex_10_3;
    QPushButton *ButtonHex_10_8;
    QPushButton *ButtonHex_8_1;
    QPushButton *ButtonHex_10_9;
    QPushButton *ButtonHex_8_3;
    QPushButton *ButtonHex_8_4;
    QPushButton *ButtonHex_8_7;
    QPushButton *ButtonHex_10_5;
    QPushButton *ButtonHex_8_5;
    QPushButton *ButtonHex_10_10;
    QPushButton *ButtonHex_8_10;
    QPushButton *ButtonHex_9_4;
    QPushButton *ButtonHex_9_8;
    QPushButton *ButtonHex_9_5;
    QPushButton *ButtonHex_9_2;
    QPushButton *ButtonHex_9_1;
    QPushButton *ButtonHex_8_6;
    QPushButton *ButtonHex_10_1;
    QPushButton *ButtonHex_10_7;
    QLabel *N1;
    QLabel *N2;
    QLabel *N3;
    QLabel *N4;
    QLabel *N5;
    QLabel *N6;
    QLabel *N8;
    QLabel *N9;
    QLabel *N7;
    QLabel *N10;
    QLabel *N11;
    QLabel *S1;
    QLabel *S2;
    QLabel *S7;
    QLabel *S4;
    QLabel *S5;
    QLabel *S6;
    QLabel *S9;
    QLabel *S10;
    QLabel *S3;
    QLabel *S8;
    QLabel *S11;
    QLabel *V1;
    QLabel *V2;
    QLabel *V3;
    QLabel *V4;
    QLabel *V5;
    QLabel *V6;
    QLabel *V7;
    QLabel *V8;
    QLabel *V9;
    QLabel *V10;
    QLabel *V11;
    QLabel *E8;
    QLabel *E11;
    QLabel *E4;
    QLabel *E2;
    QLabel *E1;
    QLabel *E6;
    QLabel *E9;
    QLabel *E7;
    QLabel *E3;
    QLabel *E10;
    QLabel *E5;
    QLabel *Turns;
    QPushButton *Patcher;
    QWidget *page_3;
    QLabel *Winner;
    QPushButton *DaRop;
    QPushButton *NuROP;
    QLabel *IntrebareROP;

    void setupUi(QFrame *HexUI)
    {
        if (HexUI->objectName().isEmpty())
            HexUI->setObjectName(QString::fromUtf8("HexUI"));
        HexUI->resize(1133, 769);
        QIcon icon;
        icon.addFile(QString::fromUtf8("../GUI pictures/bee-and-dripping-honeycomb-sticker-1561735216.3313851.png"), QSize(), QIcon::Normal, QIcon::Off);
        HexUI->setWindowIcon(icon);
        stackedWidget = new QStackedWidget(HexUI);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 1131, 771));
        stackedWidget->setAutoFillBackground(false);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        pushButton = new QPushButton(page);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(440, 530, 241, 131));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("../GUI pictures/OkHex.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton->setIcon(icon1);
        pushButton->setIconSize(QSize(400, 250));
        pushButton->setFlat(true);
        NumePlayer2_2 = new QPlainTextEdit(page);
        NumePlayer2_2->setObjectName(QString::fromUtf8("NumePlayer2_2"));
        NumePlayer2_2->setGeometry(QRect(700, 210, 291, 41));
        QFont font;
        font.setFamily(QString::fromUtf8("Constantia"));
        font.setPointSize(14);
        NumePlayer2_2->setFont(font);
        CuloarePlayer1 = new QLabel(page);
        CuloarePlayer1->setObjectName(QString::fromUtf8("CuloarePlayer1"));
        CuloarePlayer1->setGeometry(QRect(80, 330, 391, 40));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Constantia"));
        font1.setPointSize(18);
        font1.setBold(true);
        font1.setWeight(75);
        CuloarePlayer1->setFont(font1);
        CuloarePlayer1->setAlignment(Qt::AlignCenter);
        NumePlayer1_2 = new QPlainTextEdit(page);
        NumePlayer1_2->setObjectName(QString::fromUtf8("NumePlayer1_2"));
        NumePlayer1_2->setGeometry(QRect(140, 210, 291, 41));
        NumePlayer1_2->setFont(font);
        NumePlayer1 = new QLabel(page);
        NumePlayer1->setObjectName(QString::fromUtf8("NumePlayer1"));
        NumePlayer1->setGeometry(QRect(10, 150, 511, 40));
        NumePlayer1->setFont(font1);
        NumePlayer1->setAlignment(Qt::AlignCenter);
        NumePlayer2 = new QLabel(page);
        NumePlayer2->setObjectName(QString::fromUtf8("NumePlayer2"));
        NumePlayer2->setGeometry(QRect(520, 150, 621, 40));
        NumePlayer2->setFont(font1);
        NumePlayer2->setAlignment(Qt::AlignCenter);
        CuloarePlayer2 = new QLabel(page);
        CuloarePlayer2->setObjectName(QString::fromUtf8("CuloarePlayer2"));
        CuloarePlayer2->setGeometry(QRect(580, 330, 511, 40));
        CuloarePlayer2->setFont(font1);
        CuloarePlayer2->setAlignment(Qt::AlignCenter);
        comboBox_P1 = new QComboBox(page);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Day Sky/HSI_sky_001.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon2, QString());
        QIcon icon3;
        icon3.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Evergreen/HSI_evergreen_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon3, QString());
        QIcon icon4;
        icon4.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Flint/HSI_flint_002.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon4, QString());
        QIcon icon5;
        icon5.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Lemon/HSI_lemon_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon5, QString());
        QIcon icon6;
        icon6.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Orange/HSI_orange_002.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon6, QString());
        QIcon icon7;
        icon7.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Pink/HSI_pink_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon7, QString());
        QIcon icon8;
        icon8.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Red/HSI_red_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon8, QString());
        QIcon icon9;
        icon9.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Ultra/HSI_ultra_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon9, QString());
        comboBox_P1->setObjectName(QString::fromUtf8("comboBox_P1"));
        comboBox_P1->setGeometry(QRect(180, 400, 181, 71));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Comic Sans MS"));
        font2.setPointSize(16);
        comboBox_P1->setFont(font2);
        comboBox_P1->setIconSize(QSize(37, 37));
        comboBox_P2 = new QComboBox(page);
        comboBox_P2->addItem(icon2, QString());
        comboBox_P2->addItem(icon3, QString());
        comboBox_P2->addItem(icon4, QString());
        comboBox_P2->addItem(icon5, QString());
        comboBox_P2->addItem(icon6, QString());
        comboBox_P2->addItem(icon7, QString());
        comboBox_P2->addItem(icon8, QString());
        comboBox_P2->addItem(icon9, QString());
        comboBox_P2->setObjectName(QString::fromUtf8("comboBox_P2"));
        comboBox_P2->setGeometry(QRect(760, 390, 181, 71));
        comboBox_P2->setFont(font2);
        comboBox_P2->setIconSize(QSize(37, 37));
        MesajEroare = new QLabel(page);
        MesajEroare->setObjectName(QString::fromUtf8("MesajEroare"));
        MesajEroare->setGeometry(QRect(340, 670, 441, 51));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Unispace"));
        font3.setPointSize(12);
        font3.setBold(true);
        font3.setWeight(75);
        MesajEroare->setFont(font3);
        MesajEroare->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label = new QLabel(page_2);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(230, 200, 632, 392));
        label->setPixmap(QPixmap(QString::fromUtf8("../GUI pictures/FINAL/HexBoard.png")));
        ButtonHex_0_8 = new QPushButton(page_2);
        ButtonHex_0_8->setObjectName(QString::fromUtf8("ButtonHex_0_8"));
        ButtonHex_0_8->setGeometry(QRect(552, 237, 26, 26));
        ButtonHex_0_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_8->setFlat(true);
        ButtonHex_0_5 = new QPushButton(page_2);
        ButtonHex_0_5->setObjectName(QString::fromUtf8("ButtonHex_0_5"));
        ButtonHex_0_5->setGeometry(QRect(453, 237, 26, 26));
        ButtonHex_0_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_5->setFlat(true);
        ButtonHex_0_4 = new QPushButton(page_2);
        ButtonHex_0_4->setObjectName(QString::fromUtf8("ButtonHex_0_4"));
        ButtonHex_0_4->setGeometry(QRect(420, 237, 26, 26));
        ButtonHex_0_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_4->setFlat(true);
        ButtonHex_0_10 = new QPushButton(page_2);
        ButtonHex_0_10->setObjectName(QString::fromUtf8("ButtonHex_0_10"));
        ButtonHex_0_10->setGeometry(QRect(618, 237, 26, 26));
        ButtonHex_0_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_10->setFlat(true);
        ButtonHex_0_6 = new QPushButton(page_2);
        ButtonHex_0_6->setObjectName(QString::fromUtf8("ButtonHex_0_6"));
        ButtonHex_0_6->setGeometry(QRect(486, 237, 26, 26));
        ButtonHex_0_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_6->setFlat(true);
        ButtonHex_0_2 = new QPushButton(page_2);
        ButtonHex_0_2->setObjectName(QString::fromUtf8("ButtonHex_0_2"));
        ButtonHex_0_2->setGeometry(QRect(354, 237, 26, 26));
        ButtonHex_0_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_2->setFlat(true);
        ButtonHex_0_0 = new QPushButton(page_2);
        ButtonHex_0_0->setObjectName(QString::fromUtf8("ButtonHex_0_0"));
        ButtonHex_0_0->setGeometry(QRect(288, 237, 26, 26));
        ButtonHex_0_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_0->setFlat(true);
        ButtonHex_0_1 = new QPushButton(page_2);
        ButtonHex_0_1->setObjectName(QString::fromUtf8("ButtonHex_0_1"));
        ButtonHex_0_1->setGeometry(QRect(321, 237, 26, 26));
        ButtonHex_0_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_1->setFlat(true);
        ButtonHex_0_7 = new QPushButton(page_2);
        ButtonHex_0_7->setObjectName(QString::fromUtf8("ButtonHex_0_7"));
        ButtonHex_0_7->setGeometry(QRect(519, 237, 26, 26));
        ButtonHex_0_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_7->setFlat(true);
        ButtonHex_0_3 = new QPushButton(page_2);
        ButtonHex_0_3->setObjectName(QString::fromUtf8("ButtonHex_0_3"));
        ButtonHex_0_3->setGeometry(QRect(387, 237, 26, 26));
        ButtonHex_0_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_3->setFlat(true);
        ButtonHex_0_9 = new QPushButton(page_2);
        ButtonHex_0_9->setObjectName(QString::fromUtf8("ButtonHex_0_9"));
        ButtonHex_0_9->setGeometry(QRect(585, 237, 26, 26));
        ButtonHex_0_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_0_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_0_9->setFlat(true);
        ButtonHex_1_1 = new QPushButton(page_2);
        ButtonHex_1_1->setObjectName(QString::fromUtf8("ButtonHex_1_1"));
        ButtonHex_1_1->setGeometry(QRect(337, 266, 26, 26));
        ButtonHex_1_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_1->setFlat(true);
        ButtonHex_1_0 = new QPushButton(page_2);
        ButtonHex_1_0->setObjectName(QString::fromUtf8("ButtonHex_1_0"));
        ButtonHex_1_0->setGeometry(QRect(304, 266, 26, 26));
        ButtonHex_1_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_0->setFlat(true);
        ButtonHex_1_5 = new QPushButton(page_2);
        ButtonHex_1_5->setObjectName(QString::fromUtf8("ButtonHex_1_5"));
        ButtonHex_1_5->setGeometry(QRect(469, 266, 26, 26));
        ButtonHex_1_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_5->setFlat(true);
        ButtonHex_1_7 = new QPushButton(page_2);
        ButtonHex_1_7->setObjectName(QString::fromUtf8("ButtonHex_1_7"));
        ButtonHex_1_7->setGeometry(QRect(535, 266, 26, 26));
        ButtonHex_1_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_7->setFlat(true);
        ButtonHex_1_3 = new QPushButton(page_2);
        ButtonHex_1_3->setObjectName(QString::fromUtf8("ButtonHex_1_3"));
        ButtonHex_1_3->setGeometry(QRect(403, 266, 26, 26));
        ButtonHex_1_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_3->setFlat(true);
        ButtonHex_1_8 = new QPushButton(page_2);
        ButtonHex_1_8->setObjectName(QString::fromUtf8("ButtonHex_1_8"));
        ButtonHex_1_8->setGeometry(QRect(568, 266, 26, 26));
        ButtonHex_1_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_8->setFlat(true);
        ButtonHex_1_2 = new QPushButton(page_2);
        ButtonHex_1_2->setObjectName(QString::fromUtf8("ButtonHex_1_2"));
        ButtonHex_1_2->setGeometry(QRect(370, 266, 26, 26));
        ButtonHex_1_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_2->setFlat(true);
        ButtonHex_1_6 = new QPushButton(page_2);
        ButtonHex_1_6->setObjectName(QString::fromUtf8("ButtonHex_1_6"));
        ButtonHex_1_6->setGeometry(QRect(502, 266, 26, 26));
        ButtonHex_1_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_6->setFlat(true);
        ButtonHex_1_10 = new QPushButton(page_2);
        ButtonHex_1_10->setObjectName(QString::fromUtf8("ButtonHex_1_10"));
        ButtonHex_1_10->setGeometry(QRect(634, 266, 26, 26));
        ButtonHex_1_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_10->setFlat(true);
        ButtonHex_1_4 = new QPushButton(page_2);
        ButtonHex_1_4->setObjectName(QString::fromUtf8("ButtonHex_1_4"));
        ButtonHex_1_4->setGeometry(QRect(436, 266, 26, 26));
        ButtonHex_1_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_4->setFlat(true);
        ButtonHex_1_9 = new QPushButton(page_2);
        ButtonHex_1_9->setObjectName(QString::fromUtf8("ButtonHex_1_9"));
        ButtonHex_1_9->setGeometry(QRect(601, 266, 26, 26));
        ButtonHex_1_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_1_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_1_9->setFlat(true);
        ButtonHex_3_10 = new QPushButton(page_2);
        ButtonHex_3_10->setObjectName(QString::fromUtf8("ButtonHex_3_10"));
        ButtonHex_3_10->setGeometry(QRect(666, 324, 26, 26));
        ButtonHex_3_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_10->setFlat(true);
        ButtonHex_2_7 = new QPushButton(page_2);
        ButtonHex_2_7->setObjectName(QString::fromUtf8("ButtonHex_2_7"));
        ButtonHex_2_7->setGeometry(QRect(551, 295, 26, 26));
        ButtonHex_2_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_7->setFlat(true);
        ButtonHex_3_5 = new QPushButton(page_2);
        ButtonHex_3_5->setObjectName(QString::fromUtf8("ButtonHex_3_5"));
        ButtonHex_3_5->setGeometry(QRect(501, 324, 26, 26));
        ButtonHex_3_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_5->setFlat(true);
        ButtonHex_3_3 = new QPushButton(page_2);
        ButtonHex_3_3->setObjectName(QString::fromUtf8("ButtonHex_3_3"));
        ButtonHex_3_3->setGeometry(QRect(435, 324, 26, 26));
        ButtonHex_3_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_3->setFlat(true);
        ButtonHex_2_9 = new QPushButton(page_2);
        ButtonHex_2_9->setObjectName(QString::fromUtf8("ButtonHex_2_9"));
        ButtonHex_2_9->setGeometry(QRect(617, 295, 26, 26));
        ButtonHex_2_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_9->setFlat(true);
        ButtonHex_2_8 = new QPushButton(page_2);
        ButtonHex_2_8->setObjectName(QString::fromUtf8("ButtonHex_2_8"));
        ButtonHex_2_8->setGeometry(QRect(584, 295, 26, 26));
        ButtonHex_2_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_8->setFlat(true);
        ButtonHex_3_7 = new QPushButton(page_2);
        ButtonHex_3_7->setObjectName(QString::fromUtf8("ButtonHex_3_7"));
        ButtonHex_3_7->setGeometry(QRect(567, 324, 26, 26));
        ButtonHex_3_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_7->setFlat(true);
        ButtonHex_2_3 = new QPushButton(page_2);
        ButtonHex_2_3->setObjectName(QString::fromUtf8("ButtonHex_2_3"));
        ButtonHex_2_3->setGeometry(QRect(419, 295, 26, 26));
        ButtonHex_2_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_3->setFlat(true);
        ButtonHex_3_0 = new QPushButton(page_2);
        ButtonHex_3_0->setObjectName(QString::fromUtf8("ButtonHex_3_0"));
        ButtonHex_3_0->setGeometry(QRect(336, 324, 26, 26));
        ButtonHex_3_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_0->setFlat(true);
        ButtonHex_3_2 = new QPushButton(page_2);
        ButtonHex_3_2->setObjectName(QString::fromUtf8("ButtonHex_3_2"));
        ButtonHex_3_2->setGeometry(QRect(402, 324, 26, 26));
        ButtonHex_3_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_2->setFlat(true);
        ButtonHex_3_4 = new QPushButton(page_2);
        ButtonHex_3_4->setObjectName(QString::fromUtf8("ButtonHex_3_4"));
        ButtonHex_3_4->setGeometry(QRect(468, 324, 26, 26));
        ButtonHex_3_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_4->setFlat(true);
        ButtonHex_2_5 = new QPushButton(page_2);
        ButtonHex_2_5->setObjectName(QString::fromUtf8("ButtonHex_2_5"));
        ButtonHex_2_5->setGeometry(QRect(485, 295, 26, 26));
        ButtonHex_2_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_5->setFlat(true);
        ButtonHex_2_1 = new QPushButton(page_2);
        ButtonHex_2_1->setObjectName(QString::fromUtf8("ButtonHex_2_1"));
        ButtonHex_2_1->setGeometry(QRect(353, 295, 26, 26));
        ButtonHex_2_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_1->setFlat(true);
        ButtonHex_2_10 = new QPushButton(page_2);
        ButtonHex_2_10->setObjectName(QString::fromUtf8("ButtonHex_2_10"));
        ButtonHex_2_10->setGeometry(QRect(650, 295, 26, 26));
        ButtonHex_2_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_10->setFlat(true);
        ButtonHex_2_2 = new QPushButton(page_2);
        ButtonHex_2_2->setObjectName(QString::fromUtf8("ButtonHex_2_2"));
        ButtonHex_2_2->setGeometry(QRect(386, 295, 26, 26));
        ButtonHex_2_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_2->setFlat(true);
        ButtonHex_3_8 = new QPushButton(page_2);
        ButtonHex_3_8->setObjectName(QString::fromUtf8("ButtonHex_3_8"));
        ButtonHex_3_8->setGeometry(QRect(600, 324, 26, 26));
        ButtonHex_3_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_8->setFlat(true);
        ButtonHex_3_9 = new QPushButton(page_2);
        ButtonHex_3_9->setObjectName(QString::fromUtf8("ButtonHex_3_9"));
        ButtonHex_3_9->setGeometry(QRect(633, 324, 26, 26));
        ButtonHex_3_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_9->setFlat(true);
        ButtonHex_3_1 = new QPushButton(page_2);
        ButtonHex_3_1->setObjectName(QString::fromUtf8("ButtonHex_3_1"));
        ButtonHex_3_1->setGeometry(QRect(369, 324, 26, 26));
        ButtonHex_3_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_1->setFlat(true);
        ButtonHex_2_0 = new QPushButton(page_2);
        ButtonHex_2_0->setObjectName(QString::fromUtf8("ButtonHex_2_0"));
        ButtonHex_2_0->setGeometry(QRect(320, 295, 26, 26));
        ButtonHex_2_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_0->setFlat(true);
        ButtonHex_2_4 = new QPushButton(page_2);
        ButtonHex_2_4->setObjectName(QString::fromUtf8("ButtonHex_2_4"));
        ButtonHex_2_4->setGeometry(QRect(452, 295, 26, 26));
        ButtonHex_2_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_4->setFlat(true);
        ButtonHex_3_6 = new QPushButton(page_2);
        ButtonHex_3_6->setObjectName(QString::fromUtf8("ButtonHex_3_6"));
        ButtonHex_3_6->setGeometry(QRect(534, 324, 26, 26));
        ButtonHex_3_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_3_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_3_6->setFlat(true);
        ButtonHex_2_6 = new QPushButton(page_2);
        ButtonHex_2_6->setObjectName(QString::fromUtf8("ButtonHex_2_6"));
        ButtonHex_2_6->setGeometry(QRect(518, 295, 26, 26));
        ButtonHex_2_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_2_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_2_6->setFlat(true);
        ButtonHex_4_0 = new QPushButton(page_2);
        ButtonHex_4_0->setObjectName(QString::fromUtf8("ButtonHex_4_0"));
        ButtonHex_4_0->setGeometry(QRect(352, 353, 26, 26));
        ButtonHex_4_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_0->setFlat(true);
        ButtonHex_7_10 = new QPushButton(page_2);
        ButtonHex_7_10->setObjectName(QString::fromUtf8("ButtonHex_7_10"));
        ButtonHex_7_10->setGeometry(QRect(730, 440, 26, 26));
        ButtonHex_7_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_10->setFlat(true);
        ButtonHex_7_4 = new QPushButton(page_2);
        ButtonHex_7_4->setObjectName(QString::fromUtf8("ButtonHex_7_4"));
        ButtonHex_7_4->setGeometry(QRect(532, 440, 26, 26));
        ButtonHex_7_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_4->setFlat(true);
        ButtonHex_4_4 = new QPushButton(page_2);
        ButtonHex_4_4->setObjectName(QString::fromUtf8("ButtonHex_4_4"));
        ButtonHex_4_4->setGeometry(QRect(484, 353, 26, 26));
        ButtonHex_4_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_4->setFlat(true);
        ButtonHex_5_6 = new QPushButton(page_2);
        ButtonHex_5_6->setObjectName(QString::fromUtf8("ButtonHex_5_6"));
        ButtonHex_5_6->setGeometry(QRect(566, 382, 26, 26));
        ButtonHex_5_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_6->setFlat(true);
        ButtonHex_6_8 = new QPushButton(page_2);
        ButtonHex_6_8->setObjectName(QString::fromUtf8("ButtonHex_6_8"));
        ButtonHex_6_8->setGeometry(QRect(648, 411, 26, 26));
        ButtonHex_6_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_8->setFlat(true);
        ButtonHex_6_10 = new QPushButton(page_2);
        ButtonHex_6_10->setObjectName(QString::fromUtf8("ButtonHex_6_10"));
        ButtonHex_6_10->setGeometry(QRect(714, 411, 26, 26));
        ButtonHex_6_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_10->setFlat(true);
        ButtonHex_7_5 = new QPushButton(page_2);
        ButtonHex_7_5->setObjectName(QString::fromUtf8("ButtonHex_7_5"));
        ButtonHex_7_5->setGeometry(QRect(565, 440, 26, 26));
        ButtonHex_7_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_5->setFlat(true);
        ButtonHex_4_7 = new QPushButton(page_2);
        ButtonHex_4_7->setObjectName(QString::fromUtf8("ButtonHex_4_7"));
        ButtonHex_4_7->setGeometry(QRect(583, 353, 26, 26));
        ButtonHex_4_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_7->setFlat(true);
        ButtonHex_6_6 = new QPushButton(page_2);
        ButtonHex_6_6->setObjectName(QString::fromUtf8("ButtonHex_6_6"));
        ButtonHex_6_6->setGeometry(QRect(582, 411, 26, 26));
        ButtonHex_6_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_6->setFlat(true);
        ButtonHex_5_2 = new QPushButton(page_2);
        ButtonHex_5_2->setObjectName(QString::fromUtf8("ButtonHex_5_2"));
        ButtonHex_5_2->setGeometry(QRect(434, 382, 26, 26));
        ButtonHex_5_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_2->setFlat(true);
        ButtonHex_4_1 = new QPushButton(page_2);
        ButtonHex_4_1->setObjectName(QString::fromUtf8("ButtonHex_4_1"));
        ButtonHex_4_1->setGeometry(QRect(385, 353, 26, 26));
        ButtonHex_4_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_1->setFlat(true);
        ButtonHex_4_5 = new QPushButton(page_2);
        ButtonHex_4_5->setObjectName(QString::fromUtf8("ButtonHex_4_5"));
        ButtonHex_4_5->setGeometry(QRect(517, 353, 26, 26));
        ButtonHex_4_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_5->setFlat(true);
        ButtonHex_4_10 = new QPushButton(page_2);
        ButtonHex_4_10->setObjectName(QString::fromUtf8("ButtonHex_4_10"));
        ButtonHex_4_10->setGeometry(QRect(682, 353, 26, 26));
        ButtonHex_4_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_10->setFlat(true);
        ButtonHex_6_3 = new QPushButton(page_2);
        ButtonHex_6_3->setObjectName(QString::fromUtf8("ButtonHex_6_3"));
        ButtonHex_6_3->setGeometry(QRect(483, 411, 26, 26));
        ButtonHex_6_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_3->setFlat(true);
        ButtonHex_4_6 = new QPushButton(page_2);
        ButtonHex_4_6->setObjectName(QString::fromUtf8("ButtonHex_4_6"));
        ButtonHex_4_6->setGeometry(QRect(550, 353, 26, 26));
        ButtonHex_4_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_6->setFlat(true);
        ButtonHex_5_5 = new QPushButton(page_2);
        ButtonHex_5_5->setObjectName(QString::fromUtf8("ButtonHex_5_5"));
        ButtonHex_5_5->setGeometry(QRect(533, 382, 26, 26));
        ButtonHex_5_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_5->setFlat(true);
        ButtonHex_7_6 = new QPushButton(page_2);
        ButtonHex_7_6->setObjectName(QString::fromUtf8("ButtonHex_7_6"));
        ButtonHex_7_6->setGeometry(QRect(598, 440, 26, 26));
        ButtonHex_7_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_6->setFlat(true);
        ButtonHex_5_7 = new QPushButton(page_2);
        ButtonHex_5_7->setObjectName(QString::fromUtf8("ButtonHex_5_7"));
        ButtonHex_5_7->setGeometry(QRect(599, 382, 26, 26));
        ButtonHex_5_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_7->setFlat(true);
        ButtonHex_4_2 = new QPushButton(page_2);
        ButtonHex_4_2->setObjectName(QString::fromUtf8("ButtonHex_4_2"));
        ButtonHex_4_2->setGeometry(QRect(418, 353, 26, 26));
        ButtonHex_4_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_2->setFlat(true);
        ButtonHex_5_1 = new QPushButton(page_2);
        ButtonHex_5_1->setObjectName(QString::fromUtf8("ButtonHex_5_1"));
        ButtonHex_5_1->setGeometry(QRect(401, 382, 26, 26));
        ButtonHex_5_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_1->setFlat(true);
        ButtonHex_6_4 = new QPushButton(page_2);
        ButtonHex_6_4->setObjectName(QString::fromUtf8("ButtonHex_6_4"));
        ButtonHex_6_4->setGeometry(QRect(516, 411, 26, 26));
        ButtonHex_6_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_4->setFlat(true);
        ButtonHex_6_2 = new QPushButton(page_2);
        ButtonHex_6_2->setObjectName(QString::fromUtf8("ButtonHex_6_2"));
        ButtonHex_6_2->setGeometry(QRect(450, 411, 26, 26));
        ButtonHex_6_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_2->setFlat(true);
        ButtonHex_5_9 = new QPushButton(page_2);
        ButtonHex_5_9->setObjectName(QString::fromUtf8("ButtonHex_5_9"));
        ButtonHex_5_9->setGeometry(QRect(665, 382, 26, 26));
        ButtonHex_5_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_9->setFlat(true);
        ButtonHex_4_9 = new QPushButton(page_2);
        ButtonHex_4_9->setObjectName(QString::fromUtf8("ButtonHex_4_9"));
        ButtonHex_4_9->setGeometry(QRect(649, 353, 26, 26));
        ButtonHex_4_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_9->setFlat(true);
        ButtonHex_7_1 = new QPushButton(page_2);
        ButtonHex_7_1->setObjectName(QString::fromUtf8("ButtonHex_7_1"));
        ButtonHex_7_1->setGeometry(QRect(433, 440, 26, 26));
        ButtonHex_7_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_1->setFlat(true);
        ButtonHex_4_3 = new QPushButton(page_2);
        ButtonHex_4_3->setObjectName(QString::fromUtf8("ButtonHex_4_3"));
        ButtonHex_4_3->setGeometry(QRect(451, 353, 26, 26));
        ButtonHex_4_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_3->setFlat(true);
        ButtonHex_7_2 = new QPushButton(page_2);
        ButtonHex_7_2->setObjectName(QString::fromUtf8("ButtonHex_7_2"));
        ButtonHex_7_2->setGeometry(QRect(466, 440, 26, 26));
        ButtonHex_7_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_2->setFlat(true);
        ButtonHex_7_8 = new QPushButton(page_2);
        ButtonHex_7_8->setObjectName(QString::fromUtf8("ButtonHex_7_8"));
        ButtonHex_7_8->setGeometry(QRect(664, 440, 26, 26));
        ButtonHex_7_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_8->setFlat(true);
        ButtonHex_7_7 = new QPushButton(page_2);
        ButtonHex_7_7->setObjectName(QString::fromUtf8("ButtonHex_7_7"));
        ButtonHex_7_7->setGeometry(QRect(631, 440, 26, 26));
        ButtonHex_7_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_7->setFlat(true);
        ButtonHex_4_8 = new QPushButton(page_2);
        ButtonHex_4_8->setObjectName(QString::fromUtf8("ButtonHex_4_8"));
        ButtonHex_4_8->setGeometry(QRect(616, 353, 26, 26));
        ButtonHex_4_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_4_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_4_8->setFlat(true);
        ButtonHex_5_0 = new QPushButton(page_2);
        ButtonHex_5_0->setObjectName(QString::fromUtf8("ButtonHex_5_0"));
        ButtonHex_5_0->setGeometry(QRect(368, 382, 26, 26));
        ButtonHex_5_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_0->setFlat(true);
        ButtonHex_6_1 = new QPushButton(page_2);
        ButtonHex_6_1->setObjectName(QString::fromUtf8("ButtonHex_6_1"));
        ButtonHex_6_1->setGeometry(QRect(417, 411, 26, 26));
        ButtonHex_6_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_1->setFlat(true);
        ButtonHex_5_4 = new QPushButton(page_2);
        ButtonHex_5_4->setObjectName(QString::fromUtf8("ButtonHex_5_4"));
        ButtonHex_5_4->setGeometry(QRect(500, 382, 26, 26));
        ButtonHex_5_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_4->setFlat(true);
        ButtonHex_5_3 = new QPushButton(page_2);
        ButtonHex_5_3->setObjectName(QString::fromUtf8("ButtonHex_5_3"));
        ButtonHex_5_3->setGeometry(QRect(467, 382, 26, 26));
        ButtonHex_5_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_3->setFlat(true);
        ButtonHex_5_10 = new QPushButton(page_2);
        ButtonHex_5_10->setObjectName(QString::fromUtf8("ButtonHex_5_10"));
        ButtonHex_5_10->setGeometry(QRect(698, 382, 26, 26));
        ButtonHex_5_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_10->setFlat(true);
        ButtonHex_6_9 = new QPushButton(page_2);
        ButtonHex_6_9->setObjectName(QString::fromUtf8("ButtonHex_6_9"));
        ButtonHex_6_9->setGeometry(QRect(681, 411, 26, 26));
        ButtonHex_6_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_9->setFlat(true);
        ButtonHex_6_7 = new QPushButton(page_2);
        ButtonHex_6_7->setObjectName(QString::fromUtf8("ButtonHex_6_7"));
        ButtonHex_6_7->setGeometry(QRect(615, 411, 26, 26));
        ButtonHex_6_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_7->setFlat(true);
        ButtonHex_5_8 = new QPushButton(page_2);
        ButtonHex_5_8->setObjectName(QString::fromUtf8("ButtonHex_5_8"));
        ButtonHex_5_8->setGeometry(QRect(632, 382, 26, 26));
        ButtonHex_5_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_5_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_5_8->setFlat(true);
        ButtonHex_7_0 = new QPushButton(page_2);
        ButtonHex_7_0->setObjectName(QString::fromUtf8("ButtonHex_7_0"));
        ButtonHex_7_0->setGeometry(QRect(400, 440, 26, 26));
        ButtonHex_7_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_0->setFlat(true);
        ButtonHex_6_5 = new QPushButton(page_2);
        ButtonHex_6_5->setObjectName(QString::fromUtf8("ButtonHex_6_5"));
        ButtonHex_6_5->setGeometry(QRect(549, 411, 26, 26));
        ButtonHex_6_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_5->setFlat(true);
        ButtonHex_7_3 = new QPushButton(page_2);
        ButtonHex_7_3->setObjectName(QString::fromUtf8("ButtonHex_7_3"));
        ButtonHex_7_3->setGeometry(QRect(499, 440, 26, 26));
        ButtonHex_7_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_3->setFlat(true);
        ButtonHex_6_0 = new QPushButton(page_2);
        ButtonHex_6_0->setObjectName(QString::fromUtf8("ButtonHex_6_0"));
        ButtonHex_6_0->setGeometry(QRect(384, 411, 26, 26));
        ButtonHex_6_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_6_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_6_0->setFlat(true);
        ButtonHex_7_9 = new QPushButton(page_2);
        ButtonHex_7_9->setObjectName(QString::fromUtf8("ButtonHex_7_9"));
        ButtonHex_7_9->setGeometry(QRect(697, 440, 26, 26));
        ButtonHex_7_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_7_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_7_9->setFlat(true);
        ButtonHex_10_4 = new QPushButton(page_2);
        ButtonHex_10_4->setObjectName(QString::fromUtf8("ButtonHex_10_4"));
        ButtonHex_10_4->setGeometry(QRect(580, 527, 26, 26));
        ButtonHex_10_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_4->setFlat(true);
        ButtonHex_8_8 = new QPushButton(page_2);
        ButtonHex_8_8->setObjectName(QString::fromUtf8("ButtonHex_8_8"));
        ButtonHex_8_8->setGeometry(QRect(680, 469, 26, 26));
        ButtonHex_8_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_8->setFlat(true);
        ButtonHex_10_6 = new QPushButton(page_2);
        ButtonHex_10_6->setObjectName(QString::fromUtf8("ButtonHex_10_6"));
        ButtonHex_10_6->setGeometry(QRect(646, 527, 26, 26));
        ButtonHex_10_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_6->setFlat(true);
        ButtonHex_8_0 = new QPushButton(page_2);
        ButtonHex_8_0->setObjectName(QString::fromUtf8("ButtonHex_8_0"));
        ButtonHex_8_0->setGeometry(QRect(416, 469, 26, 26));
        ButtonHex_8_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_0->setFlat(true);
        ButtonHex_8_9 = new QPushButton(page_2);
        ButtonHex_8_9->setObjectName(QString::fromUtf8("ButtonHex_8_9"));
        ButtonHex_8_9->setGeometry(QRect(713, 469, 26, 26));
        ButtonHex_8_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_9->setFlat(true);
        ButtonHex_9_6 = new QPushButton(page_2);
        ButtonHex_9_6->setObjectName(QString::fromUtf8("ButtonHex_9_6"));
        ButtonHex_9_6->setGeometry(QRect(630, 498, 26, 26));
        ButtonHex_9_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_6->setFlat(true);
        ButtonHex_9_9 = new QPushButton(page_2);
        ButtonHex_9_9->setObjectName(QString::fromUtf8("ButtonHex_9_9"));
        ButtonHex_9_9->setGeometry(QRect(729, 498, 26, 26));
        ButtonHex_9_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_9->setFlat(true);
        ButtonHex_10_2 = new QPushButton(page_2);
        ButtonHex_10_2->setObjectName(QString::fromUtf8("ButtonHex_10_2"));
        ButtonHex_10_2->setGeometry(QRect(514, 527, 26, 26));
        ButtonHex_10_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_2->setFlat(true);
        ButtonHex_10_0 = new QPushButton(page_2);
        ButtonHex_10_0->setObjectName(QString::fromUtf8("ButtonHex_10_0"));
        ButtonHex_10_0->setGeometry(QRect(448, 527, 26, 26));
        ButtonHex_10_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_0->setFlat(true);
        ButtonHex_8_2 = new QPushButton(page_2);
        ButtonHex_8_2->setObjectName(QString::fromUtf8("ButtonHex_8_2"));
        ButtonHex_8_2->setGeometry(QRect(482, 469, 26, 26));
        ButtonHex_8_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_2->setFlat(true);
        ButtonHex_9_7 = new QPushButton(page_2);
        ButtonHex_9_7->setObjectName(QString::fromUtf8("ButtonHex_9_7"));
        ButtonHex_9_7->setGeometry(QRect(663, 498, 26, 26));
        ButtonHex_9_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_7->setFlat(true);
        ButtonHex_9_3 = new QPushButton(page_2);
        ButtonHex_9_3->setObjectName(QString::fromUtf8("ButtonHex_9_3"));
        ButtonHex_9_3->setGeometry(QRect(531, 498, 26, 26));
        ButtonHex_9_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_3->setFlat(true);
        ButtonHex_9_10 = new QPushButton(page_2);
        ButtonHex_9_10->setObjectName(QString::fromUtf8("ButtonHex_9_10"));
        ButtonHex_9_10->setGeometry(QRect(762, 498, 26, 26));
        ButtonHex_9_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_10->setFlat(true);
        ButtonHex_9_0 = new QPushButton(page_2);
        ButtonHex_9_0->setObjectName(QString::fromUtf8("ButtonHex_9_0"));
        ButtonHex_9_0->setGeometry(QRect(432, 498, 26, 26));
        ButtonHex_9_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_0->setFlat(true);
        ButtonHex_10_3 = new QPushButton(page_2);
        ButtonHex_10_3->setObjectName(QString::fromUtf8("ButtonHex_10_3"));
        ButtonHex_10_3->setGeometry(QRect(547, 527, 26, 26));
        ButtonHex_10_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_3->setFlat(true);
        ButtonHex_10_8 = new QPushButton(page_2);
        ButtonHex_10_8->setObjectName(QString::fromUtf8("ButtonHex_10_8"));
        ButtonHex_10_8->setGeometry(QRect(712, 527, 26, 26));
        ButtonHex_10_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_8->setFlat(true);
        ButtonHex_8_1 = new QPushButton(page_2);
        ButtonHex_8_1->setObjectName(QString::fromUtf8("ButtonHex_8_1"));
        ButtonHex_8_1->setGeometry(QRect(449, 469, 26, 26));
        ButtonHex_8_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_1->setFlat(true);
        ButtonHex_10_9 = new QPushButton(page_2);
        ButtonHex_10_9->setObjectName(QString::fromUtf8("ButtonHex_10_9"));
        ButtonHex_10_9->setGeometry(QRect(745, 527, 26, 26));
        ButtonHex_10_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_9->setFlat(true);
        ButtonHex_8_3 = new QPushButton(page_2);
        ButtonHex_8_3->setObjectName(QString::fromUtf8("ButtonHex_8_3"));
        ButtonHex_8_3->setGeometry(QRect(515, 469, 26, 26));
        ButtonHex_8_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_3->setFlat(true);
        ButtonHex_8_4 = new QPushButton(page_2);
        ButtonHex_8_4->setObjectName(QString::fromUtf8("ButtonHex_8_4"));
        ButtonHex_8_4->setGeometry(QRect(548, 469, 26, 26));
        ButtonHex_8_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_4->setFlat(true);
        ButtonHex_8_7 = new QPushButton(page_2);
        ButtonHex_8_7->setObjectName(QString::fromUtf8("ButtonHex_8_7"));
        ButtonHex_8_7->setGeometry(QRect(647, 469, 26, 26));
        ButtonHex_8_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_7->setFlat(true);
        ButtonHex_10_5 = new QPushButton(page_2);
        ButtonHex_10_5->setObjectName(QString::fromUtf8("ButtonHex_10_5"));
        ButtonHex_10_5->setGeometry(QRect(613, 527, 26, 26));
        ButtonHex_10_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_5->setFlat(true);
        ButtonHex_8_5 = new QPushButton(page_2);
        ButtonHex_8_5->setObjectName(QString::fromUtf8("ButtonHex_8_5"));
        ButtonHex_8_5->setGeometry(QRect(581, 469, 26, 26));
        ButtonHex_8_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_5->setFlat(true);
        ButtonHex_10_10 = new QPushButton(page_2);
        ButtonHex_10_10->setObjectName(QString::fromUtf8("ButtonHex_10_10"));
        ButtonHex_10_10->setGeometry(QRect(778, 527, 26, 26));
        ButtonHex_10_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_10->setFlat(true);
        ButtonHex_8_10 = new QPushButton(page_2);
        ButtonHex_8_10->setObjectName(QString::fromUtf8("ButtonHex_8_10"));
        ButtonHex_8_10->setGeometry(QRect(746, 469, 26, 26));
        ButtonHex_8_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_10->setFlat(true);
        ButtonHex_9_4 = new QPushButton(page_2);
        ButtonHex_9_4->setObjectName(QString::fromUtf8("ButtonHex_9_4"));
        ButtonHex_9_4->setGeometry(QRect(564, 498, 26, 26));
        ButtonHex_9_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_4->setFlat(true);
        ButtonHex_9_8 = new QPushButton(page_2);
        ButtonHex_9_8->setObjectName(QString::fromUtf8("ButtonHex_9_8"));
        ButtonHex_9_8->setGeometry(QRect(696, 498, 26, 26));
        ButtonHex_9_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_8->setFlat(true);
        ButtonHex_9_5 = new QPushButton(page_2);
        ButtonHex_9_5->setObjectName(QString::fromUtf8("ButtonHex_9_5"));
        ButtonHex_9_5->setGeometry(QRect(597, 498, 26, 26));
        ButtonHex_9_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_5->setFlat(true);
        ButtonHex_9_2 = new QPushButton(page_2);
        ButtonHex_9_2->setObjectName(QString::fromUtf8("ButtonHex_9_2"));
        ButtonHex_9_2->setGeometry(QRect(498, 498, 26, 26));
        ButtonHex_9_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_2->setFlat(true);
        ButtonHex_9_1 = new QPushButton(page_2);
        ButtonHex_9_1->setObjectName(QString::fromUtf8("ButtonHex_9_1"));
        ButtonHex_9_1->setGeometry(QRect(465, 498, 26, 26));
        ButtonHex_9_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_9_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_9_1->setFlat(true);
        ButtonHex_8_6 = new QPushButton(page_2);
        ButtonHex_8_6->setObjectName(QString::fromUtf8("ButtonHex_8_6"));
        ButtonHex_8_6->setGeometry(QRect(614, 469, 26, 26));
        ButtonHex_8_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_8_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_8_6->setFlat(true);
        ButtonHex_10_1 = new QPushButton(page_2);
        ButtonHex_10_1->setObjectName(QString::fromUtf8("ButtonHex_10_1"));
        ButtonHex_10_1->setGeometry(QRect(481, 527, 26, 26));
        ButtonHex_10_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_1->setFlat(true);
        ButtonHex_10_7 = new QPushButton(page_2);
        ButtonHex_10_7->setObjectName(QString::fromUtf8("ButtonHex_10_7"));
        ButtonHex_10_7->setGeometry(QRect(679, 527, 26, 26));
        ButtonHex_10_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonHex_10_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonHex_10_7->setFlat(true);
        N1 = new QLabel(page_2);
        N1->setObjectName(QString::fromUtf8("N1"));
        N1->setGeometry(QRect(263, 200, 44, 44));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(N1->sizePolicy().hasHeightForWidth());
        N1->setSizePolicy(sizePolicy);
        N2 = new QLabel(page_2);
        N2->setObjectName(QString::fromUtf8("N2"));
        N2->setGeometry(QRect(296, 200, 44, 44));
        sizePolicy.setHeightForWidth(N2->sizePolicy().hasHeightForWidth());
        N2->setSizePolicy(sizePolicy);
        N3 = new QLabel(page_2);
        N3->setObjectName(QString::fromUtf8("N3"));
        N3->setGeometry(QRect(329, 200, 44, 44));
        sizePolicy.setHeightForWidth(N3->sizePolicy().hasHeightForWidth());
        N3->setSizePolicy(sizePolicy);
        N4 = new QLabel(page_2);
        N4->setObjectName(QString::fromUtf8("N4"));
        N4->setGeometry(QRect(362, 200, 44, 44));
        sizePolicy.setHeightForWidth(N4->sizePolicy().hasHeightForWidth());
        N4->setSizePolicy(sizePolicy);
        N5 = new QLabel(page_2);
        N5->setObjectName(QString::fromUtf8("N5"));
        N5->setGeometry(QRect(395, 200, 44, 44));
        sizePolicy.setHeightForWidth(N5->sizePolicy().hasHeightForWidth());
        N5->setSizePolicy(sizePolicy);
        N6 = new QLabel(page_2);
        N6->setObjectName(QString::fromUtf8("N6"));
        N6->setGeometry(QRect(428, 200, 44, 44));
        sizePolicy.setHeightForWidth(N6->sizePolicy().hasHeightForWidth());
        N6->setSizePolicy(sizePolicy);
        N8 = new QLabel(page_2);
        N8->setObjectName(QString::fromUtf8("N8"));
        N8->setGeometry(QRect(494, 200, 44, 44));
        sizePolicy.setHeightForWidth(N8->sizePolicy().hasHeightForWidth());
        N8->setSizePolicy(sizePolicy);
        N9 = new QLabel(page_2);
        N9->setObjectName(QString::fromUtf8("N9"));
        N9->setGeometry(QRect(527, 200, 44, 44));
        sizePolicy.setHeightForWidth(N9->sizePolicy().hasHeightForWidth());
        N9->setSizePolicy(sizePolicy);
        N7 = new QLabel(page_2);
        N7->setObjectName(QString::fromUtf8("N7"));
        N7->setGeometry(QRect(461, 200, 44, 44));
        sizePolicy.setHeightForWidth(N7->sizePolicy().hasHeightForWidth());
        N7->setSizePolicy(sizePolicy);
        N10 = new QLabel(page_2);
        N10->setObjectName(QString::fromUtf8("N10"));
        N10->setGeometry(QRect(560, 200, 44, 44));
        sizePolicy.setHeightForWidth(N10->sizePolicy().hasHeightForWidth());
        N10->setSizePolicy(sizePolicy);
        N11 = new QLabel(page_2);
        N11->setObjectName(QString::fromUtf8("N11"));
        N11->setGeometry(QRect(593, 200, 44, 44));
        sizePolicy.setHeightForWidth(N11->sizePolicy().hasHeightForWidth());
        N11->setSizePolicy(sizePolicy);
        S1 = new QLabel(page_2);
        S1->setObjectName(QString::fromUtf8("S1"));
        S1->setGeometry(QRect(455, 548, 44, 44));
        sizePolicy.setHeightForWidth(S1->sizePolicy().hasHeightForWidth());
        S1->setSizePolicy(sizePolicy);
        S2 = new QLabel(page_2);
        S2->setObjectName(QString::fromUtf8("S2"));
        S2->setGeometry(QRect(488, 548, 44, 44));
        sizePolicy.setHeightForWidth(S2->sizePolicy().hasHeightForWidth());
        S2->setSizePolicy(sizePolicy);
        S7 = new QLabel(page_2);
        S7->setObjectName(QString::fromUtf8("S7"));
        S7->setGeometry(QRect(653, 548, 44, 44));
        sizePolicy.setHeightForWidth(S7->sizePolicy().hasHeightForWidth());
        S7->setSizePolicy(sizePolicy);
        S4 = new QLabel(page_2);
        S4->setObjectName(QString::fromUtf8("S4"));
        S4->setGeometry(QRect(554, 548, 44, 44));
        sizePolicy.setHeightForWidth(S4->sizePolicy().hasHeightForWidth());
        S4->setSizePolicy(sizePolicy);
        S5 = new QLabel(page_2);
        S5->setObjectName(QString::fromUtf8("S5"));
        S5->setGeometry(QRect(587, 548, 44, 44));
        sizePolicy.setHeightForWidth(S5->sizePolicy().hasHeightForWidth());
        S5->setSizePolicy(sizePolicy);
        S6 = new QLabel(page_2);
        S6->setObjectName(QString::fromUtf8("S6"));
        S6->setGeometry(QRect(620, 548, 44, 44));
        sizePolicy.setHeightForWidth(S6->sizePolicy().hasHeightForWidth());
        S6->setSizePolicy(sizePolicy);
        S9 = new QLabel(page_2);
        S9->setObjectName(QString::fromUtf8("S9"));
        S9->setGeometry(QRect(719, 548, 44, 44));
        sizePolicy.setHeightForWidth(S9->sizePolicy().hasHeightForWidth());
        S9->setSizePolicy(sizePolicy);
        S10 = new QLabel(page_2);
        S10->setObjectName(QString::fromUtf8("S10"));
        S10->setGeometry(QRect(752, 548, 44, 44));
        sizePolicy.setHeightForWidth(S10->sizePolicy().hasHeightForWidth());
        S10->setSizePolicy(sizePolicy);
        S3 = new QLabel(page_2);
        S3->setObjectName(QString::fromUtf8("S3"));
        S3->setGeometry(QRect(521, 548, 44, 44));
        sizePolicy.setHeightForWidth(S3->sizePolicy().hasHeightForWidth());
        S3->setSizePolicy(sizePolicy);
        S8 = new QLabel(page_2);
        S8->setObjectName(QString::fromUtf8("S8"));
        S8->setGeometry(QRect(686, 548, 44, 44));
        sizePolicy.setHeightForWidth(S8->sizePolicy().hasHeightForWidth());
        S8->setSizePolicy(sizePolicy);
        S11 = new QLabel(page_2);
        S11->setObjectName(QString::fromUtf8("S11"));
        S11->setGeometry(QRect(785, 548, 44, 44));
        sizePolicy.setHeightForWidth(S11->sizePolicy().hasHeightForWidth());
        S11->setSizePolicy(sizePolicy);
        V1 = new QLabel(page_2);
        V1->setObjectName(QString::fromUtf8("V1"));
        V1->setGeometry(QRect(246, 229, 44, 44));
        sizePolicy.setHeightForWidth(V1->sizePolicy().hasHeightForWidth());
        V1->setSizePolicy(sizePolicy);
        V2 = new QLabel(page_2);
        V2->setObjectName(QString::fromUtf8("V2"));
        V2->setGeometry(QRect(262, 258, 44, 44));
        sizePolicy.setHeightForWidth(V2->sizePolicy().hasHeightForWidth());
        V2->setSizePolicy(sizePolicy);
        V3 = new QLabel(page_2);
        V3->setObjectName(QString::fromUtf8("V3"));
        V3->setGeometry(QRect(278, 287, 44, 44));
        sizePolicy.setHeightForWidth(V3->sizePolicy().hasHeightForWidth());
        V3->setSizePolicy(sizePolicy);
        V4 = new QLabel(page_2);
        V4->setObjectName(QString::fromUtf8("V4"));
        V4->setGeometry(QRect(294, 316, 44, 44));
        sizePolicy.setHeightForWidth(V4->sizePolicy().hasHeightForWidth());
        V4->setSizePolicy(sizePolicy);
        V5 = new QLabel(page_2);
        V5->setObjectName(QString::fromUtf8("V5"));
        V5->setGeometry(QRect(310, 345, 44, 44));
        sizePolicy.setHeightForWidth(V5->sizePolicy().hasHeightForWidth());
        V5->setSizePolicy(sizePolicy);
        V6 = new QLabel(page_2);
        V6->setObjectName(QString::fromUtf8("V6"));
        V6->setGeometry(QRect(326, 374, 44, 44));
        sizePolicy.setHeightForWidth(V6->sizePolicy().hasHeightForWidth());
        V6->setSizePolicy(sizePolicy);
        V7 = new QLabel(page_2);
        V7->setObjectName(QString::fromUtf8("V7"));
        V7->setGeometry(QRect(342, 403, 44, 44));
        sizePolicy.setHeightForWidth(V7->sizePolicy().hasHeightForWidth());
        V7->setSizePolicy(sizePolicy);
        V8 = new QLabel(page_2);
        V8->setObjectName(QString::fromUtf8("V8"));
        V8->setGeometry(QRect(358, 432, 44, 44));
        sizePolicy.setHeightForWidth(V8->sizePolicy().hasHeightForWidth());
        V8->setSizePolicy(sizePolicy);
        V9 = new QLabel(page_2);
        V9->setObjectName(QString::fromUtf8("V9"));
        V9->setGeometry(QRect(374, 461, 44, 44));
        sizePolicy.setHeightForWidth(V9->sizePolicy().hasHeightForWidth());
        V9->setSizePolicy(sizePolicy);
        V10 = new QLabel(page_2);
        V10->setObjectName(QString::fromUtf8("V10"));
        V10->setGeometry(QRect(390, 490, 44, 44));
        sizePolicy.setHeightForWidth(V10->sizePolicy().hasHeightForWidth());
        V10->setSizePolicy(sizePolicy);
        V11 = new QLabel(page_2);
        V11->setObjectName(QString::fromUtf8("V11"));
        V11->setGeometry(QRect(406, 519, 44, 44));
        sizePolicy.setHeightForWidth(V11->sizePolicy().hasHeightForWidth());
        V11->setSizePolicy(sizePolicy);
        E8 = new QLabel(page_2);
        E8->setObjectName(QString::fromUtf8("E8"));
        E8->setGeometry(QRect(754, 432, 44, 44));
        sizePolicy.setHeightForWidth(E8->sizePolicy().hasHeightForWidth());
        E8->setSizePolicy(sizePolicy);
        E11 = new QLabel(page_2);
        E11->setObjectName(QString::fromUtf8("E11"));
        E11->setGeometry(QRect(802, 519, 44, 44));
        sizePolicy.setHeightForWidth(E11->sizePolicy().hasHeightForWidth());
        E11->setSizePolicy(sizePolicy);
        E4 = new QLabel(page_2);
        E4->setObjectName(QString::fromUtf8("E4"));
        E4->setGeometry(QRect(690, 316, 44, 44));
        sizePolicy.setHeightForWidth(E4->sizePolicy().hasHeightForWidth());
        E4->setSizePolicy(sizePolicy);
        E2 = new QLabel(page_2);
        E2->setObjectName(QString::fromUtf8("E2"));
        E2->setGeometry(QRect(658, 258, 44, 44));
        sizePolicy.setHeightForWidth(E2->sizePolicy().hasHeightForWidth());
        E2->setSizePolicy(sizePolicy);
        E1 = new QLabel(page_2);
        E1->setObjectName(QString::fromUtf8("E1"));
        E1->setGeometry(QRect(642, 229, 44, 44));
        sizePolicy.setHeightForWidth(E1->sizePolicy().hasHeightForWidth());
        E1->setSizePolicy(sizePolicy);
        E6 = new QLabel(page_2);
        E6->setObjectName(QString::fromUtf8("E6"));
        E6->setGeometry(QRect(722, 374, 44, 44));
        sizePolicy.setHeightForWidth(E6->sizePolicy().hasHeightForWidth());
        E6->setSizePolicy(sizePolicy);
        E9 = new QLabel(page_2);
        E9->setObjectName(QString::fromUtf8("E9"));
        E9->setGeometry(QRect(770, 461, 44, 44));
        sizePolicy.setHeightForWidth(E9->sizePolicy().hasHeightForWidth());
        E9->setSizePolicy(sizePolicy);
        E7 = new QLabel(page_2);
        E7->setObjectName(QString::fromUtf8("E7"));
        E7->setGeometry(QRect(738, 403, 44, 44));
        sizePolicy.setHeightForWidth(E7->sizePolicy().hasHeightForWidth());
        E7->setSizePolicy(sizePolicy);
        E3 = new QLabel(page_2);
        E3->setObjectName(QString::fromUtf8("E3"));
        E3->setGeometry(QRect(674, 287, 44, 44));
        sizePolicy.setHeightForWidth(E3->sizePolicy().hasHeightForWidth());
        E3->setSizePolicy(sizePolicy);
        E10 = new QLabel(page_2);
        E10->setObjectName(QString::fromUtf8("E10"));
        E10->setGeometry(QRect(786, 490, 44, 44));
        sizePolicy.setHeightForWidth(E10->sizePolicy().hasHeightForWidth());
        E10->setSizePolicy(sizePolicy);
        E5 = new QLabel(page_2);
        E5->setObjectName(QString::fromUtf8("E5"));
        E5->setGeometry(QRect(706, 345, 44, 44));
        sizePolicy.setHeightForWidth(E5->sizePolicy().hasHeightForWidth());
        E5->setSizePolicy(sizePolicy);
        Turns = new QLabel(page_2);
        Turns->setObjectName(QString::fromUtf8("Turns"));
        Turns->setGeometry(QRect(250, 60, 611, 71));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Constantia"));
        font4.setPointSize(28);
        Turns->setFont(font4);
        Turns->setAlignment(Qt::AlignCenter);
        Patcher = new QPushButton(page_2);
        Patcher->setObjectName(QString::fromUtf8("Patcher"));
        Patcher->setGeometry(QRect(1020, 70, 26, 26));
        Patcher->setCursor(QCursor(Qt::PointingHandCursor));
        Patcher->setStyleSheet(QString::fromUtf8("border: none;"));
        Patcher->setFlat(true);
        stackedWidget->addWidget(page_2);
        label->raise();
        N3->raise();
        N2->raise();
        N1->raise();
        ButtonHex_1_1->raise();
        ButtonHex_1_0->raise();
        ButtonHex_1_5->raise();
        ButtonHex_1_7->raise();
        ButtonHex_1_3->raise();
        ButtonHex_1_8->raise();
        ButtonHex_1_2->raise();
        ButtonHex_1_6->raise();
        ButtonHex_1_10->raise();
        ButtonHex_1_4->raise();
        ButtonHex_1_9->raise();
        ButtonHex_3_10->raise();
        ButtonHex_2_7->raise();
        ButtonHex_3_5->raise();
        ButtonHex_3_3->raise();
        ButtonHex_2_9->raise();
        ButtonHex_2_8->raise();
        ButtonHex_3_7->raise();
        ButtonHex_2_3->raise();
        ButtonHex_3_0->raise();
        ButtonHex_3_2->raise();
        ButtonHex_3_4->raise();
        ButtonHex_2_5->raise();
        ButtonHex_2_1->raise();
        ButtonHex_2_10->raise();
        ButtonHex_2_2->raise();
        ButtonHex_3_8->raise();
        ButtonHex_3_9->raise();
        ButtonHex_3_1->raise();
        ButtonHex_2_0->raise();
        ButtonHex_2_4->raise();
        ButtonHex_3_6->raise();
        ButtonHex_2_6->raise();
        ButtonHex_4_0->raise();
        ButtonHex_7_10->raise();
        ButtonHex_7_4->raise();
        ButtonHex_4_4->raise();
        ButtonHex_5_6->raise();
        ButtonHex_6_8->raise();
        ButtonHex_6_10->raise();
        ButtonHex_7_5->raise();
        ButtonHex_4_7->raise();
        ButtonHex_6_6->raise();
        ButtonHex_5_2->raise();
        ButtonHex_4_1->raise();
        ButtonHex_4_5->raise();
        ButtonHex_4_10->raise();
        ButtonHex_6_3->raise();
        ButtonHex_4_6->raise();
        ButtonHex_5_5->raise();
        ButtonHex_7_6->raise();
        ButtonHex_5_7->raise();
        ButtonHex_4_2->raise();
        ButtonHex_5_1->raise();
        ButtonHex_6_4->raise();
        ButtonHex_6_2->raise();
        ButtonHex_5_9->raise();
        ButtonHex_4_9->raise();
        ButtonHex_7_1->raise();
        ButtonHex_4_3->raise();
        ButtonHex_7_2->raise();
        ButtonHex_7_8->raise();
        ButtonHex_7_7->raise();
        ButtonHex_4_8->raise();
        ButtonHex_5_0->raise();
        ButtonHex_6_1->raise();
        ButtonHex_5_4->raise();
        ButtonHex_5_3->raise();
        ButtonHex_5_10->raise();
        ButtonHex_6_9->raise();
        ButtonHex_6_7->raise();
        ButtonHex_5_8->raise();
        ButtonHex_7_0->raise();
        ButtonHex_6_5->raise();
        ButtonHex_7_3->raise();
        ButtonHex_6_0->raise();
        ButtonHex_7_9->raise();
        ButtonHex_10_4->raise();
        ButtonHex_8_8->raise();
        ButtonHex_10_6->raise();
        ButtonHex_8_0->raise();
        ButtonHex_8_9->raise();
        ButtonHex_9_6->raise();
        ButtonHex_9_9->raise();
        ButtonHex_10_2->raise();
        ButtonHex_10_0->raise();
        ButtonHex_8_2->raise();
        ButtonHex_9_7->raise();
        ButtonHex_9_3->raise();
        ButtonHex_9_10->raise();
        ButtonHex_9_0->raise();
        ButtonHex_10_3->raise();
        ButtonHex_10_8->raise();
        ButtonHex_8_1->raise();
        ButtonHex_10_9->raise();
        ButtonHex_8_3->raise();
        ButtonHex_8_4->raise();
        ButtonHex_8_7->raise();
        ButtonHex_10_5->raise();
        ButtonHex_8_5->raise();
        ButtonHex_10_10->raise();
        ButtonHex_8_10->raise();
        ButtonHex_9_4->raise();
        ButtonHex_9_8->raise();
        ButtonHex_9_5->raise();
        ButtonHex_9_2->raise();
        ButtonHex_9_1->raise();
        ButtonHex_8_6->raise();
        ButtonHex_10_1->raise();
        ButtonHex_10_7->raise();
        ButtonHex_0_4->raise();
        ButtonHex_0_6->raise();
        ButtonHex_0_0->raise();
        ButtonHex_0_7->raise();
        ButtonHex_0_5->raise();
        ButtonHex_0_9->raise();
        ButtonHex_0_10->raise();
        ButtonHex_0_8->raise();
        ButtonHex_0_1->raise();
        ButtonHex_0_2->raise();
        ButtonHex_0_3->raise();
        N4->raise();
        N5->raise();
        N6->raise();
        N8->raise();
        N9->raise();
        N7->raise();
        N10->raise();
        N11->raise();
        S1->raise();
        S2->raise();
        S7->raise();
        S4->raise();
        S5->raise();
        S6->raise();
        S9->raise();
        S10->raise();
        S3->raise();
        S8->raise();
        S11->raise();
        V1->raise();
        V2->raise();
        V3->raise();
        V4->raise();
        V5->raise();
        V6->raise();
        V7->raise();
        V8->raise();
        V9->raise();
        V10->raise();
        V11->raise();
        E8->raise();
        E11->raise();
        E4->raise();
        E2->raise();
        E1->raise();
        E6->raise();
        E9->raise();
        E7->raise();
        E3->raise();
        E10->raise();
        E5->raise();
        Turns->raise();
        Patcher->raise();
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        Winner = new QLabel(page_3);
        Winner->setObjectName(QString::fromUtf8("Winner"));
        Winner->setGeometry(QRect(90, 150, 961, 411));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Constantia"));
        font5.setPointSize(36);
        font5.setBold(true);
        font5.setWeight(75);
        Winner->setFont(font5);
        Winner->setAlignment(Qt::AlignCenter);
        DaRop = new QPushButton(page_3);
        DaRop->setObjectName(QString::fromUtf8("DaRop"));
        DaRop->setGeometry(QRect(220, 390, 251, 121));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Constantia"));
        font6.setPointSize(26);
        DaRop->setFont(font6);
        QIcon icon10;
        icon10.addFile(QString::fromUtf8("../GUI pictures/Da_Hex.png"), QSize(), QIcon::Normal, QIcon::Off);
        DaRop->setIcon(icon10);
        DaRop->setIconSize(QSize(400, 250));
        DaRop->setFlat(true);
        NuROP = new QPushButton(page_3);
        NuROP->setObjectName(QString::fromUtf8("NuROP"));
        NuROP->setGeometry(QRect(600, 390, 251, 121));
        NuROP->setFont(font6);
        QIcon icon11;
        icon11.addFile(QString::fromUtf8("../GUI pictures/Nu_Hex.png"), QSize(), QIcon::Normal, QIcon::Off);
        NuROP->setIcon(icon11);
        NuROP->setIconSize(QSize(400, 250));
        NuROP->setFlat(true);
        IntrebareROP = new QLabel(page_3);
        IntrebareROP->setObjectName(QString::fromUtf8("IntrebareROP"));
        IntrebareROP->setGeometry(QRect(50, 170, 1041, 151));
        IntrebareROP->setFont(font5);
        IntrebareROP->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_3);

        retranslateUi(HexUI);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(HexUI);
    } // setupUi

    void retranslateUi(QFrame *HexUI)
    {
        HexUI->setWindowTitle(QCoreApplication::translate("HexUI", "Hex Game", nullptr));
        pushButton->setText(QString());
        NumePlayer2_2->setPlainText(QCoreApplication::translate("HexUI", "Player2", nullptr));
        CuloarePlayer1->setText(QCoreApplication::translate("HexUI", "Alegeti culoarea primului jucator:", nullptr));
        NumePlayer1_2->setPlainText(QCoreApplication::translate("HexUI", "Player1", nullptr));
        NumePlayer1->setText(QCoreApplication::translate("HexUI", "Introduceti numele primului jucator:", nullptr));
        NumePlayer2->setText(QCoreApplication::translate("HexUI", "Introduceti numele celui de-al doileai jucator:", nullptr));
        CuloarePlayer2->setText(QCoreApplication::translate("HexUI", "Alegeti culoarea celui de-al doileai jucator:", nullptr));
        comboBox_P1->setItemText(0, QCoreApplication::translate("HexUI", "Albastru", nullptr));
        comboBox_P1->setItemText(1, QCoreApplication::translate("HexUI", "Verde", nullptr));
        comboBox_P1->setItemText(2, QCoreApplication::translate("HexUI", "Negru", nullptr));
        comboBox_P1->setItemText(3, QCoreApplication::translate("HexUI", "Galben", nullptr));
        comboBox_P1->setItemText(4, QCoreApplication::translate("HexUI", "Portocaliu", nullptr));
        comboBox_P1->setItemText(5, QCoreApplication::translate("HexUI", "Roz", nullptr));
        comboBox_P1->setItemText(6, QCoreApplication::translate("HexUI", "Rosu", nullptr));
        comboBox_P1->setItemText(7, QCoreApplication::translate("HexUI", "Mov", nullptr));

        comboBox_P2->setItemText(0, QCoreApplication::translate("HexUI", "Albastru", nullptr));
        comboBox_P2->setItemText(1, QCoreApplication::translate("HexUI", "Verde", nullptr));
        comboBox_P2->setItemText(2, QCoreApplication::translate("HexUI", "Negru", nullptr));
        comboBox_P2->setItemText(3, QCoreApplication::translate("HexUI", "Galben", nullptr));
        comboBox_P2->setItemText(4, QCoreApplication::translate("HexUI", "Portocaliu", nullptr));
        comboBox_P2->setItemText(5, QCoreApplication::translate("HexUI", "Roz", nullptr));
        comboBox_P2->setItemText(6, QCoreApplication::translate("HexUI", "Rosu", nullptr));
        comboBox_P2->setItemText(7, QCoreApplication::translate("HexUI", "Mov", nullptr));

        MesajEroare->setText(QString());
        label->setText(QString());
        ButtonHex_0_8->setText(QString());
        ButtonHex_0_5->setText(QString());
        ButtonHex_0_4->setText(QString());
        ButtonHex_0_10->setText(QString());
        ButtonHex_0_6->setText(QString());
        ButtonHex_0_2->setText(QString());
        ButtonHex_0_0->setText(QString());
        ButtonHex_0_1->setText(QString());
        ButtonHex_0_7->setText(QString());
        ButtonHex_0_3->setText(QString());
        ButtonHex_0_9->setText(QString());
        ButtonHex_1_1->setText(QString());
        ButtonHex_1_0->setText(QString());
        ButtonHex_1_5->setText(QString());
        ButtonHex_1_7->setText(QString());
        ButtonHex_1_3->setText(QString());
        ButtonHex_1_8->setText(QString());
        ButtonHex_1_2->setText(QString());
        ButtonHex_1_6->setText(QString());
        ButtonHex_1_10->setText(QString());
        ButtonHex_1_4->setText(QString());
        ButtonHex_1_9->setText(QString());
        ButtonHex_3_10->setText(QString());
        ButtonHex_2_7->setText(QString());
        ButtonHex_3_5->setText(QString());
        ButtonHex_3_3->setText(QString());
        ButtonHex_2_9->setText(QString());
        ButtonHex_2_8->setText(QString());
        ButtonHex_3_7->setText(QString());
        ButtonHex_2_3->setText(QString());
        ButtonHex_3_0->setText(QString());
        ButtonHex_3_2->setText(QString());
        ButtonHex_3_4->setText(QString());
        ButtonHex_2_5->setText(QString());
        ButtonHex_2_1->setText(QString());
        ButtonHex_2_10->setText(QString());
        ButtonHex_2_2->setText(QString());
        ButtonHex_3_8->setText(QString());
        ButtonHex_3_9->setText(QString());
        ButtonHex_3_1->setText(QString());
        ButtonHex_2_0->setText(QString());
        ButtonHex_2_4->setText(QString());
        ButtonHex_3_6->setText(QString());
        ButtonHex_2_6->setText(QString());
        ButtonHex_4_0->setText(QString());
        ButtonHex_7_10->setText(QString());
        ButtonHex_7_4->setText(QString());
        ButtonHex_4_4->setText(QString());
        ButtonHex_5_6->setText(QString());
        ButtonHex_6_8->setText(QString());
        ButtonHex_6_10->setText(QString());
        ButtonHex_7_5->setText(QString());
        ButtonHex_4_7->setText(QString());
        ButtonHex_6_6->setText(QString());
        ButtonHex_5_2->setText(QString());
        ButtonHex_4_1->setText(QString());
        ButtonHex_4_5->setText(QString());
        ButtonHex_4_10->setText(QString());
        ButtonHex_6_3->setText(QString());
        ButtonHex_4_6->setText(QString());
        ButtonHex_5_5->setText(QString());
        ButtonHex_7_6->setText(QString());
        ButtonHex_5_7->setText(QString());
        ButtonHex_4_2->setText(QString());
        ButtonHex_5_1->setText(QString());
        ButtonHex_6_4->setText(QString());
        ButtonHex_6_2->setText(QString());
        ButtonHex_5_9->setText(QString());
        ButtonHex_4_9->setText(QString());
        ButtonHex_7_1->setText(QString());
        ButtonHex_4_3->setText(QString());
        ButtonHex_7_2->setText(QString());
        ButtonHex_7_8->setText(QString());
        ButtonHex_7_7->setText(QString());
        ButtonHex_4_8->setText(QString());
        ButtonHex_5_0->setText(QString());
        ButtonHex_6_1->setText(QString());
        ButtonHex_5_4->setText(QString());
        ButtonHex_5_3->setText(QString());
        ButtonHex_5_10->setText(QString());
        ButtonHex_6_9->setText(QString());
        ButtonHex_6_7->setText(QString());
        ButtonHex_5_8->setText(QString());
        ButtonHex_7_0->setText(QString());
        ButtonHex_6_5->setText(QString());
        ButtonHex_7_3->setText(QString());
        ButtonHex_6_0->setText(QString());
        ButtonHex_7_9->setText(QString());
        ButtonHex_10_4->setText(QString());
        ButtonHex_8_8->setText(QString());
        ButtonHex_10_6->setText(QString());
        ButtonHex_8_0->setText(QString());
        ButtonHex_8_9->setText(QString());
        ButtonHex_9_6->setText(QString());
        ButtonHex_9_9->setText(QString());
        ButtonHex_10_2->setText(QString());
        ButtonHex_10_0->setText(QString());
        ButtonHex_8_2->setText(QString());
        ButtonHex_9_7->setText(QString());
        ButtonHex_9_3->setText(QString());
        ButtonHex_9_10->setText(QString());
        ButtonHex_9_0->setText(QString());
        ButtonHex_10_3->setText(QString());
        ButtonHex_10_8->setText(QString());
        ButtonHex_8_1->setText(QString());
        ButtonHex_10_9->setText(QString());
        ButtonHex_8_3->setText(QString());
        ButtonHex_8_4->setText(QString());
        ButtonHex_8_7->setText(QString());
        ButtonHex_10_5->setText(QString());
        ButtonHex_8_5->setText(QString());
        ButtonHex_10_10->setText(QString());
        ButtonHex_8_10->setText(QString());
        ButtonHex_9_4->setText(QString());
        ButtonHex_9_8->setText(QString());
        ButtonHex_9_5->setText(QString());
        ButtonHex_9_2->setText(QString());
        ButtonHex_9_1->setText(QString());
        ButtonHex_8_6->setText(QString());
        ButtonHex_10_1->setText(QString());
        ButtonHex_10_7->setText(QString());
        N1->setText(QString());
        N2->setText(QString());
        N3->setText(QString());
        N4->setText(QString());
        N5->setText(QString());
        N6->setText(QString());
        N8->setText(QString());
        N9->setText(QString());
        N7->setText(QString());
        N10->setText(QString());
        N11->setText(QString());
        S1->setText(QString());
        S2->setText(QString());
        S7->setText(QString());
        S4->setText(QString());
        S5->setText(QString());
        S6->setText(QString());
        S9->setText(QString());
        S10->setText(QString());
        S3->setText(QString());
        S8->setText(QString());
        S11->setText(QString());
        V1->setText(QString());
        V2->setText(QString());
        V3->setText(QString());
        V4->setText(QString());
        V5->setText(QString());
        V6->setText(QString());
        V7->setText(QString());
        V8->setText(QString());
        V9->setText(QString());
        V10->setText(QString());
        V11->setText(QString());
        E8->setText(QString());
        E11->setText(QString());
        E4->setText(QString());
        E2->setText(QString());
        E1->setText(QString());
        E6->setText(QString());
        E9->setText(QString());
        E7->setText(QString());
        E3->setText(QString());
        E10->setText(QString());
        E5->setText(QString());
        Turns->setText(QString());
        Patcher->setText(QString());
        Winner->setText(QString());
        DaRop->setText(QString());
        NuROP->setText(QString());
        IntrebareROP->setText(QCoreApplication::translate("HexUI", "Doriti sa preluati miscarea primului jucator?", nullptr));
    } // retranslateUi

};

namespace Ui {
    class HexUI: public Ui_HexUI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HEXUI_H
