/********************************************************************************
** Form generated from reading UI file 'yui.ui'
**
** Created by: Qt User Interface Compiler version 5.13.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_YUI_H
#define UI_YUI_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_YUI
{
public:
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *MesajEroare;
    QPushButton *pushButton;
    QComboBox *comboBox_P1;
    QLabel *CuloarePlayer1;
    QPlainTextEdit *NumePlayer1_2;
    QLabel *NumePlayer1;
    QComboBox *comboBox_P2;
    QPlainTextEdit *NumePlayer2_2;
    QLabel *CuloarePlayer2;
    QLabel *NumePlayer2;
    QWidget *page_2;
    QLabel *label;
    QPushButton *ButtonY_1_0;
    QPushButton *ButtonY_0_0;
    QPushButton *ButtonY_1_1;
    QPushButton *ButtonY_2_0;
    QPushButton *ButtonY_2_1;
    QPushButton *ButtonY_2_2;
    QPushButton *ButtonY_3_0;
    QPushButton *ButtonY_3_1;
    QPushButton *ButtonY_3_2;
    QPushButton *ButtonY_3_3;
    QPushButton *ButtonY_4_0;
    QPushButton *ButtonY_4_1;
    QPushButton *ButtonY_4_2;
    QPushButton *ButtonY_4_3;
    QPushButton *ButtonY_4_4;
    QPushButton *ButtonY_5_0;
    QPushButton *ButtonY_5_1;
    QPushButton *ButtonY_5_2;
    QPushButton *ButtonY_5_3;
    QPushButton *ButtonY_5_4;
    QPushButton *ButtonY_5_5;
    QPushButton *ButtonY_6_0;
    QPushButton *ButtonY_6_1;
    QPushButton *ButtonY_6_2;
    QPushButton *ButtonY_6_3;
    QPushButton *ButtonY_6_4;
    QPushButton *ButtonY_6_5;
    QPushButton *ButtonY_6_6;
    QPushButton *ButtonY_7_0;
    QPushButton *ButtonY_7_1;
    QPushButton *ButtonY_7_2;
    QPushButton *ButtonY_7_3;
    QPushButton *ButtonY_7_4;
    QPushButton *ButtonY_7_5;
    QPushButton *ButtonY_7_6;
    QPushButton *ButtonY_7_7;
    QPushButton *ButtonY_8_0;
    QPushButton *ButtonY_8_1;
    QPushButton *ButtonY_8_2;
    QPushButton *ButtonY_8_3;
    QPushButton *ButtonY_8_4;
    QPushButton *ButtonY_8_5;
    QPushButton *ButtonY_8_6;
    QPushButton *ButtonY_8_7;
    QPushButton *ButtonY_8_8;
    QPushButton *ButtonY_9_0;
    QPushButton *ButtonY_9_1;
    QPushButton *ButtonY_9_2;
    QPushButton *ButtonY_9_3;
    QPushButton *ButtonY_9_4;
    QPushButton *ButtonY_9_5;
    QPushButton *ButtonY_9_6;
    QPushButton *ButtonY_9_7;
    QPushButton *ButtonY_9_8;
    QPushButton *ButtonY_9_9;
    QPushButton *ButtonY_10_0;
    QPushButton *ButtonY_10_1;
    QPushButton *ButtonY_10_2;
    QPushButton *ButtonY_10_3;
    QPushButton *ButtonY_10_4;
    QPushButton *ButtonY_10_5;
    QPushButton *ButtonY_10_6;
    QPushButton *ButtonY_10_7;
    QPushButton *ButtonY_10_8;
    QPushButton *ButtonY_10_9;
    QPushButton *ButtonY_10_10;
    QPushButton *ButtonY_11_0;
    QPushButton *ButtonY_11_1;
    QPushButton *ButtonY_11_2;
    QPushButton *ButtonY_11_3;
    QPushButton *ButtonY_11_4;
    QPushButton *ButtonY_11_5;
    QPushButton *ButtonY_11_6;
    QPushButton *ButtonY_11_7;
    QPushButton *ButtonY_11_8;
    QPushButton *ButtonY_11_9;
    QPushButton *ButtonY_11_10;
    QPushButton *ButtonY_11_11;
    QPushButton *ButtonY_12_0;
    QPushButton *ButtonY_12_1;
    QPushButton *ButtonY_12_2;
    QPushButton *ButtonY_12_3;
    QPushButton *ButtonY_12_4;
    QPushButton *ButtonY_12_5;
    QPushButton *ButtonY_12_6;
    QPushButton *ButtonY_12_7;
    QPushButton *ButtonY_12_8;
    QPushButton *ButtonY_12_9;
    QPushButton *ButtonY_12_10;
    QPushButton *ButtonY_12_11;
    QPushButton *ButtonY_12_12;
    QPushButton *ButtonY_13_0;
    QPushButton *ButtonY_13_1;
    QPushButton *ButtonY_13_2;
    QPushButton *ButtonY_13_3;
    QPushButton *ButtonY_13_4;
    QPushButton *ButtonY_13_5;
    QPushButton *ButtonY_13_6;
    QPushButton *ButtonY_13_7;
    QPushButton *ButtonY_13_8;
    QPushButton *ButtonY_13_9;
    QPushButton *ButtonY_13_10;
    QPushButton *ButtonY_13_11;
    QPushButton *ButtonY_13_12;
    QPushButton *ButtonY_13_13;
    QPushButton *Patcher;
    QLabel *Turns;
    QWidget *page_3;
    QLabel *IntrebareROP;
    QPushButton *DaRop;
    QPushButton *NuROP;
    QLabel *Winner;

    void setupUi(QFrame *YUI)
    {
        if (YUI->objectName().isEmpty())
            YUI->setObjectName(QString::fromUtf8("YUI"));
        YUI->resize(1133, 776);
        QIcon icon;
        icon.addFile(QString::fromUtf8("../GUI pictures/bee-and-dripping-honeycomb-sticker-1561735216.3313851.png"), QSize(), QIcon::Normal, QIcon::Off);
        YUI->setWindowIcon(icon);
        stackedWidget = new QStackedWidget(YUI);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 1131, 771));
        stackedWidget->setBaseSize(QSize(10, 10));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        MesajEroare = new QLabel(page);
        MesajEroare->setObjectName(QString::fromUtf8("MesajEroare"));
        MesajEroare->setGeometry(QRect(340, 680, 441, 51));
        QFont font;
        font.setFamily(QString::fromUtf8("Unispace"));
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        MesajEroare->setFont(font);
        MesajEroare->setAlignment(Qt::AlignCenter);
        pushButton = new QPushButton(page);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(410, 560, 251, 111));
        QSizePolicy sizePolicy(QSizePolicy::Maximum, QSizePolicy::Maximum);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(pushButton->sizePolicy().hasHeightForWidth());
        pushButton->setSizePolicy(sizePolicy);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("../GUI pictures/OkY.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton->setIcon(icon1);
        pushButton->setIconSize(QSize(400, 250));
        pushButton->setFlat(true);
        comboBox_P1 = new QComboBox(page);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Day Sky/HSI_sky_001.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon2, QString());
        QIcon icon3;
        icon3.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Evergreen/HSI_evergreen_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon3, QString());
        QIcon icon4;
        icon4.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Flint/HSI_flint_002.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon4, QString());
        QIcon icon5;
        icon5.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Lemon/HSI_lemon_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon5, QString());
        QIcon icon6;
        icon6.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Orange/HSI_orange_002.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon6, QString());
        QIcon icon7;
        icon7.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Pink/HSI_pink_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon7, QString());
        QIcon icon8;
        icon8.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Red/HSI_red_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon8, QString());
        QIcon icon9;
        icon9.addFile(QString::fromUtf8("../GUI pictures/Hexagons/HSI - Ultra/HSI_ultra_004.png"), QSize(), QIcon::Normal, QIcon::Off);
        comboBox_P1->addItem(icon9, QString());
        comboBox_P1->setObjectName(QString::fromUtf8("comboBox_P1"));
        comboBox_P1->setGeometry(QRect(170, 400, 181, 71));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Comic Sans MS"));
        font1.setPointSize(16);
        comboBox_P1->setFont(font1);
        comboBox_P1->setIconSize(QSize(37, 37));
        CuloarePlayer1 = new QLabel(page);
        CuloarePlayer1->setObjectName(QString::fromUtf8("CuloarePlayer1"));
        CuloarePlayer1->setGeometry(QRect(70, 330, 391, 40));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Constantia"));
        font2.setPointSize(18);
        font2.setBold(true);
        font2.setWeight(75);
        CuloarePlayer1->setFont(font2);
        CuloarePlayer1->setAlignment(Qt::AlignCenter);
        NumePlayer1_2 = new QPlainTextEdit(page);
        NumePlayer1_2->setObjectName(QString::fromUtf8("NumePlayer1_2"));
        NumePlayer1_2->setGeometry(QRect(130, 210, 291, 41));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Constantia"));
        font3.setPointSize(14);
        NumePlayer1_2->setFont(font3);
        NumePlayer1 = new QLabel(page);
        NumePlayer1->setObjectName(QString::fromUtf8("NumePlayer1"));
        NumePlayer1->setGeometry(QRect(0, 150, 511, 40));
        NumePlayer1->setFont(font2);
        NumePlayer1->setAlignment(Qt::AlignCenter);
        comboBox_P2 = new QComboBox(page);
        comboBox_P2->addItem(icon2, QString());
        comboBox_P2->addItem(icon3, QString());
        comboBox_P2->addItem(icon4, QString());
        comboBox_P2->addItem(icon5, QString());
        comboBox_P2->addItem(icon6, QString());
        comboBox_P2->addItem(icon7, QString());
        comboBox_P2->addItem(icon8, QString());
        comboBox_P2->addItem(icon9, QString());
        comboBox_P2->setObjectName(QString::fromUtf8("comboBox_P2"));
        comboBox_P2->setGeometry(QRect(750, 390, 181, 71));
        comboBox_P2->setFont(font1);
        comboBox_P2->setIconSize(QSize(37, 37));
        NumePlayer2_2 = new QPlainTextEdit(page);
        NumePlayer2_2->setObjectName(QString::fromUtf8("NumePlayer2_2"));
        NumePlayer2_2->setGeometry(QRect(690, 210, 291, 41));
        NumePlayer2_2->setFont(font3);
        CuloarePlayer2 = new QLabel(page);
        CuloarePlayer2->setObjectName(QString::fromUtf8("CuloarePlayer2"));
        CuloarePlayer2->setGeometry(QRect(570, 330, 511, 40));
        CuloarePlayer2->setFont(font2);
        CuloarePlayer2->setAlignment(Qt::AlignCenter);
        NumePlayer2 = new QLabel(page);
        NumePlayer2->setObjectName(QString::fromUtf8("NumePlayer2"));
        NumePlayer2->setGeometry(QRect(510, 150, 621, 40));
        NumePlayer2->setFont(font2);
        NumePlayer2->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label = new QLabel(page_2);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(310, 220, 473, 419));
        label->setPixmap(QPixmap(QString::fromUtf8("../GUI pictures/FINAL/YBoard.png")));
        ButtonY_1_0 = new QPushButton(page_2);
        ButtonY_1_0->setObjectName(QString::fromUtf8("ButtonY_1_0"));
        ButtonY_1_0->setGeometry(QRect(523, 257, 26, 26));
        ButtonY_1_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_1_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_1_0->setFlat(true);
        ButtonY_0_0 = new QPushButton(page_2);
        ButtonY_0_0->setObjectName(QString::fromUtf8("ButtonY_0_0"));
        ButtonY_0_0->setGeometry(QRect(540, 228, 26, 26));
        ButtonY_0_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_0_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_0_0->setFlat(true);
        ButtonY_1_1 = new QPushButton(page_2);
        ButtonY_1_1->setObjectName(QString::fromUtf8("ButtonY_1_1"));
        ButtonY_1_1->setGeometry(QRect(556, 257, 26, 26));
        ButtonY_1_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_1_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_1_1->setFlat(true);
        ButtonY_2_0 = new QPushButton(page_2);
        ButtonY_2_0->setObjectName(QString::fromUtf8("ButtonY_2_0"));
        ButtonY_2_0->setGeometry(QRect(506, 286, 26, 26));
        ButtonY_2_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_2_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_2_0->setFlat(true);
        ButtonY_2_1 = new QPushButton(page_2);
        ButtonY_2_1->setObjectName(QString::fromUtf8("ButtonY_2_1"));
        ButtonY_2_1->setGeometry(QRect(539, 286, 26, 26));
        ButtonY_2_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_2_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_2_1->setFlat(true);
        ButtonY_2_2 = new QPushButton(page_2);
        ButtonY_2_2->setObjectName(QString::fromUtf8("ButtonY_2_2"));
        ButtonY_2_2->setGeometry(QRect(572, 286, 26, 26));
        ButtonY_2_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_2_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_2_2->setFlat(true);
        ButtonY_3_0 = new QPushButton(page_2);
        ButtonY_3_0->setObjectName(QString::fromUtf8("ButtonY_3_0"));
        ButtonY_3_0->setGeometry(QRect(489, 315, 26, 26));
        ButtonY_3_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_3_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_3_0->setFlat(true);
        ButtonY_3_1 = new QPushButton(page_2);
        ButtonY_3_1->setObjectName(QString::fromUtf8("ButtonY_3_1"));
        ButtonY_3_1->setGeometry(QRect(522, 315, 26, 26));
        ButtonY_3_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_3_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_3_1->setFlat(true);
        ButtonY_3_2 = new QPushButton(page_2);
        ButtonY_3_2->setObjectName(QString::fromUtf8("ButtonY_3_2"));
        ButtonY_3_2->setGeometry(QRect(555, 315, 26, 26));
        ButtonY_3_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_3_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_3_2->setFlat(true);
        ButtonY_3_3 = new QPushButton(page_2);
        ButtonY_3_3->setObjectName(QString::fromUtf8("ButtonY_3_3"));
        ButtonY_3_3->setGeometry(QRect(588, 315, 26, 26));
        ButtonY_3_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_3_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_3_3->setFlat(true);
        ButtonY_4_0 = new QPushButton(page_2);
        ButtonY_4_0->setObjectName(QString::fromUtf8("ButtonY_4_0"));
        ButtonY_4_0->setGeometry(QRect(472, 344, 26, 26));
        ButtonY_4_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_4_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_4_0->setFlat(true);
        ButtonY_4_1 = new QPushButton(page_2);
        ButtonY_4_1->setObjectName(QString::fromUtf8("ButtonY_4_1"));
        ButtonY_4_1->setGeometry(QRect(505, 344, 26, 26));
        ButtonY_4_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_4_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_4_1->setFlat(true);
        ButtonY_4_2 = new QPushButton(page_2);
        ButtonY_4_2->setObjectName(QString::fromUtf8("ButtonY_4_2"));
        ButtonY_4_2->setGeometry(QRect(538, 344, 26, 26));
        ButtonY_4_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_4_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_4_2->setFlat(true);
        ButtonY_4_3 = new QPushButton(page_2);
        ButtonY_4_3->setObjectName(QString::fromUtf8("ButtonY_4_3"));
        ButtonY_4_3->setGeometry(QRect(571, 344, 26, 26));
        ButtonY_4_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_4_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_4_3->setFlat(true);
        ButtonY_4_4 = new QPushButton(page_2);
        ButtonY_4_4->setObjectName(QString::fromUtf8("ButtonY_4_4"));
        ButtonY_4_4->setGeometry(QRect(604, 344, 26, 26));
        ButtonY_4_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_4_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_4_4->setFlat(true);
        ButtonY_5_0 = new QPushButton(page_2);
        ButtonY_5_0->setObjectName(QString::fromUtf8("ButtonY_5_0"));
        ButtonY_5_0->setGeometry(QRect(455, 373, 26, 26));
        ButtonY_5_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_5_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_5_0->setFlat(true);
        ButtonY_5_1 = new QPushButton(page_2);
        ButtonY_5_1->setObjectName(QString::fromUtf8("ButtonY_5_1"));
        ButtonY_5_1->setGeometry(QRect(488, 373, 26, 26));
        ButtonY_5_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_5_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_5_1->setFlat(true);
        ButtonY_5_2 = new QPushButton(page_2);
        ButtonY_5_2->setObjectName(QString::fromUtf8("ButtonY_5_2"));
        ButtonY_5_2->setGeometry(QRect(521, 373, 26, 26));
        ButtonY_5_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_5_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_5_2->setFlat(true);
        ButtonY_5_3 = new QPushButton(page_2);
        ButtonY_5_3->setObjectName(QString::fromUtf8("ButtonY_5_3"));
        ButtonY_5_3->setGeometry(QRect(554, 373, 26, 26));
        ButtonY_5_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_5_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_5_3->setFlat(true);
        ButtonY_5_4 = new QPushButton(page_2);
        ButtonY_5_4->setObjectName(QString::fromUtf8("ButtonY_5_4"));
        ButtonY_5_4->setGeometry(QRect(587, 373, 26, 26));
        ButtonY_5_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_5_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_5_4->setFlat(true);
        ButtonY_5_5 = new QPushButton(page_2);
        ButtonY_5_5->setObjectName(QString::fromUtf8("ButtonY_5_5"));
        ButtonY_5_5->setGeometry(QRect(620, 373, 26, 26));
        ButtonY_5_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_5_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_5_5->setFlat(true);
        ButtonY_6_0 = new QPushButton(page_2);
        ButtonY_6_0->setObjectName(QString::fromUtf8("ButtonY_6_0"));
        ButtonY_6_0->setGeometry(QRect(438, 402, 26, 26));
        ButtonY_6_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_6_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_6_0->setFlat(true);
        ButtonY_6_1 = new QPushButton(page_2);
        ButtonY_6_1->setObjectName(QString::fromUtf8("ButtonY_6_1"));
        ButtonY_6_1->setGeometry(QRect(471, 402, 26, 26));
        ButtonY_6_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_6_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_6_1->setFlat(true);
        ButtonY_6_2 = new QPushButton(page_2);
        ButtonY_6_2->setObjectName(QString::fromUtf8("ButtonY_6_2"));
        ButtonY_6_2->setGeometry(QRect(504, 402, 26, 26));
        ButtonY_6_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_6_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_6_2->setFlat(true);
        ButtonY_6_3 = new QPushButton(page_2);
        ButtonY_6_3->setObjectName(QString::fromUtf8("ButtonY_6_3"));
        ButtonY_6_3->setGeometry(QRect(537, 402, 26, 26));
        ButtonY_6_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_6_3->setMouseTracking(false);
        ButtonY_6_3->setTabletTracking(false);
        ButtonY_6_3->setFocusPolicy(Qt::StrongFocus);
        ButtonY_6_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_6_3->setFlat(true);
        ButtonY_6_4 = new QPushButton(page_2);
        ButtonY_6_4->setObjectName(QString::fromUtf8("ButtonY_6_4"));
        ButtonY_6_4->setGeometry(QRect(570, 402, 26, 26));
        ButtonY_6_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_6_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_6_4->setFlat(true);
        ButtonY_6_5 = new QPushButton(page_2);
        ButtonY_6_5->setObjectName(QString::fromUtf8("ButtonY_6_5"));
        ButtonY_6_5->setGeometry(QRect(603, 402, 26, 26));
        ButtonY_6_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_6_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_6_5->setFlat(true);
        ButtonY_6_6 = new QPushButton(page_2);
        ButtonY_6_6->setObjectName(QString::fromUtf8("ButtonY_6_6"));
        ButtonY_6_6->setGeometry(QRect(636, 402, 26, 26));
        ButtonY_6_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_6_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_6_6->setFlat(true);
        ButtonY_7_0 = new QPushButton(page_2);
        ButtonY_7_0->setObjectName(QString::fromUtf8("ButtonY_7_0"));
        ButtonY_7_0->setGeometry(QRect(421, 431, 26, 26));
        ButtonY_7_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_7_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_7_0->setFlat(true);
        ButtonY_7_1 = new QPushButton(page_2);
        ButtonY_7_1->setObjectName(QString::fromUtf8("ButtonY_7_1"));
        ButtonY_7_1->setGeometry(QRect(454, 431, 26, 26));
        ButtonY_7_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_7_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_7_1->setFlat(true);
        ButtonY_7_2 = new QPushButton(page_2);
        ButtonY_7_2->setObjectName(QString::fromUtf8("ButtonY_7_2"));
        ButtonY_7_2->setGeometry(QRect(487, 431, 26, 26));
        ButtonY_7_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_7_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_7_2->setFlat(true);
        ButtonY_7_3 = new QPushButton(page_2);
        ButtonY_7_3->setObjectName(QString::fromUtf8("ButtonY_7_3"));
        ButtonY_7_3->setGeometry(QRect(520, 431, 26, 26));
        ButtonY_7_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_7_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_7_3->setFlat(true);
        ButtonY_7_4 = new QPushButton(page_2);
        ButtonY_7_4->setObjectName(QString::fromUtf8("ButtonY_7_4"));
        ButtonY_7_4->setGeometry(QRect(553, 431, 26, 26));
        ButtonY_7_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_7_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_7_4->setFlat(true);
        ButtonY_7_5 = new QPushButton(page_2);
        ButtonY_7_5->setObjectName(QString::fromUtf8("ButtonY_7_5"));
        ButtonY_7_5->setGeometry(QRect(586, 431, 26, 26));
        ButtonY_7_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_7_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_7_5->setFlat(true);
        ButtonY_7_6 = new QPushButton(page_2);
        ButtonY_7_6->setObjectName(QString::fromUtf8("ButtonY_7_6"));
        ButtonY_7_6->setGeometry(QRect(619, 431, 26, 26));
        ButtonY_7_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_7_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_7_6->setFlat(true);
        ButtonY_7_7 = new QPushButton(page_2);
        ButtonY_7_7->setObjectName(QString::fromUtf8("ButtonY_7_7"));
        ButtonY_7_7->setGeometry(QRect(652, 431, 26, 26));
        ButtonY_7_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_7_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_7_7->setFlat(true);
        ButtonY_8_0 = new QPushButton(page_2);
        ButtonY_8_0->setObjectName(QString::fromUtf8("ButtonY_8_0"));
        ButtonY_8_0->setGeometry(QRect(404, 460, 26, 26));
        ButtonY_8_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_0->setFlat(true);
        ButtonY_8_1 = new QPushButton(page_2);
        ButtonY_8_1->setObjectName(QString::fromUtf8("ButtonY_8_1"));
        ButtonY_8_1->setGeometry(QRect(437, 460, 26, 26));
        ButtonY_8_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_1->setFlat(true);
        ButtonY_8_2 = new QPushButton(page_2);
        ButtonY_8_2->setObjectName(QString::fromUtf8("ButtonY_8_2"));
        ButtonY_8_2->setGeometry(QRect(470, 460, 26, 26));
        ButtonY_8_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_2->setFlat(true);
        ButtonY_8_3 = new QPushButton(page_2);
        ButtonY_8_3->setObjectName(QString::fromUtf8("ButtonY_8_3"));
        ButtonY_8_3->setGeometry(QRect(503, 460, 26, 26));
        ButtonY_8_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_3->setFlat(true);
        ButtonY_8_4 = new QPushButton(page_2);
        ButtonY_8_4->setObjectName(QString::fromUtf8("ButtonY_8_4"));
        ButtonY_8_4->setGeometry(QRect(536, 460, 26, 26));
        ButtonY_8_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_4->setFlat(true);
        ButtonY_8_5 = new QPushButton(page_2);
        ButtonY_8_5->setObjectName(QString::fromUtf8("ButtonY_8_5"));
        ButtonY_8_5->setGeometry(QRect(569, 460, 26, 26));
        ButtonY_8_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_5->setFlat(true);
        ButtonY_8_6 = new QPushButton(page_2);
        ButtonY_8_6->setObjectName(QString::fromUtf8("ButtonY_8_6"));
        ButtonY_8_6->setGeometry(QRect(602, 460, 26, 26));
        ButtonY_8_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_6->setFlat(true);
        ButtonY_8_7 = new QPushButton(page_2);
        ButtonY_8_7->setObjectName(QString::fromUtf8("ButtonY_8_7"));
        ButtonY_8_7->setGeometry(QRect(635, 460, 26, 26));
        ButtonY_8_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_7->setFlat(true);
        ButtonY_8_8 = new QPushButton(page_2);
        ButtonY_8_8->setObjectName(QString::fromUtf8("ButtonY_8_8"));
        ButtonY_8_8->setGeometry(QRect(668, 460, 26, 26));
        ButtonY_8_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_8_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_8_8->setFlat(true);
        ButtonY_9_0 = new QPushButton(page_2);
        ButtonY_9_0->setObjectName(QString::fromUtf8("ButtonY_9_0"));
        ButtonY_9_0->setGeometry(QRect(387, 489, 26, 26));
        ButtonY_9_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_0->setFlat(true);
        ButtonY_9_1 = new QPushButton(page_2);
        ButtonY_9_1->setObjectName(QString::fromUtf8("ButtonY_9_1"));
        ButtonY_9_1->setGeometry(QRect(420, 489, 26, 26));
        ButtonY_9_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_1->setFlat(true);
        ButtonY_9_2 = new QPushButton(page_2);
        ButtonY_9_2->setObjectName(QString::fromUtf8("ButtonY_9_2"));
        ButtonY_9_2->setGeometry(QRect(453, 489, 26, 26));
        ButtonY_9_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_2->setFlat(true);
        ButtonY_9_3 = new QPushButton(page_2);
        ButtonY_9_3->setObjectName(QString::fromUtf8("ButtonY_9_3"));
        ButtonY_9_3->setGeometry(QRect(486, 489, 26, 26));
        ButtonY_9_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_3->setFlat(true);
        ButtonY_9_4 = new QPushButton(page_2);
        ButtonY_9_4->setObjectName(QString::fromUtf8("ButtonY_9_4"));
        ButtonY_9_4->setGeometry(QRect(519, 489, 26, 26));
        ButtonY_9_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_4->setFlat(true);
        ButtonY_9_5 = new QPushButton(page_2);
        ButtonY_9_5->setObjectName(QString::fromUtf8("ButtonY_9_5"));
        ButtonY_9_5->setGeometry(QRect(552, 489, 26, 26));
        ButtonY_9_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_5->setFlat(true);
        ButtonY_9_6 = new QPushButton(page_2);
        ButtonY_9_6->setObjectName(QString::fromUtf8("ButtonY_9_6"));
        ButtonY_9_6->setGeometry(QRect(585, 489, 26, 26));
        ButtonY_9_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_6->setFlat(true);
        ButtonY_9_7 = new QPushButton(page_2);
        ButtonY_9_7->setObjectName(QString::fromUtf8("ButtonY_9_7"));
        ButtonY_9_7->setGeometry(QRect(618, 489, 26, 26));
        ButtonY_9_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_7->setFlat(true);
        ButtonY_9_8 = new QPushButton(page_2);
        ButtonY_9_8->setObjectName(QString::fromUtf8("ButtonY_9_8"));
        ButtonY_9_8->setGeometry(QRect(651, 489, 26, 26));
        ButtonY_9_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_8->setFlat(true);
        ButtonY_9_9 = new QPushButton(page_2);
        ButtonY_9_9->setObjectName(QString::fromUtf8("ButtonY_9_9"));
        ButtonY_9_9->setGeometry(QRect(684, 489, 26, 26));
        ButtonY_9_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_9_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_9_9->setFlat(true);
        ButtonY_10_0 = new QPushButton(page_2);
        ButtonY_10_0->setObjectName(QString::fromUtf8("ButtonY_10_0"));
        ButtonY_10_0->setGeometry(QRect(370, 518, 26, 26));
        ButtonY_10_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_0->setFlat(true);
        ButtonY_10_1 = new QPushButton(page_2);
        ButtonY_10_1->setObjectName(QString::fromUtf8("ButtonY_10_1"));
        ButtonY_10_1->setGeometry(QRect(403, 518, 26, 26));
        ButtonY_10_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_1->setFlat(true);
        ButtonY_10_2 = new QPushButton(page_2);
        ButtonY_10_2->setObjectName(QString::fromUtf8("ButtonY_10_2"));
        ButtonY_10_2->setGeometry(QRect(436, 518, 26, 26));
        ButtonY_10_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_2->setFlat(true);
        ButtonY_10_3 = new QPushButton(page_2);
        ButtonY_10_3->setObjectName(QString::fromUtf8("ButtonY_10_3"));
        ButtonY_10_3->setGeometry(QRect(469, 518, 26, 26));
        ButtonY_10_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_3->setFlat(true);
        ButtonY_10_4 = new QPushButton(page_2);
        ButtonY_10_4->setObjectName(QString::fromUtf8("ButtonY_10_4"));
        ButtonY_10_4->setGeometry(QRect(502, 518, 26, 26));
        ButtonY_10_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_4->setFlat(true);
        ButtonY_10_5 = new QPushButton(page_2);
        ButtonY_10_5->setObjectName(QString::fromUtf8("ButtonY_10_5"));
        ButtonY_10_5->setGeometry(QRect(535, 518, 26, 26));
        ButtonY_10_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_5->setFlat(true);
        ButtonY_10_6 = new QPushButton(page_2);
        ButtonY_10_6->setObjectName(QString::fromUtf8("ButtonY_10_6"));
        ButtonY_10_6->setGeometry(QRect(568, 518, 26, 26));
        ButtonY_10_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_6->setFlat(true);
        ButtonY_10_7 = new QPushButton(page_2);
        ButtonY_10_7->setObjectName(QString::fromUtf8("ButtonY_10_7"));
        ButtonY_10_7->setGeometry(QRect(601, 518, 26, 26));
        ButtonY_10_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_7->setFlat(true);
        ButtonY_10_8 = new QPushButton(page_2);
        ButtonY_10_8->setObjectName(QString::fromUtf8("ButtonY_10_8"));
        ButtonY_10_8->setGeometry(QRect(634, 518, 26, 26));
        ButtonY_10_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_8->setFlat(true);
        ButtonY_10_9 = new QPushButton(page_2);
        ButtonY_10_9->setObjectName(QString::fromUtf8("ButtonY_10_9"));
        ButtonY_10_9->setGeometry(QRect(667, 518, 26, 26));
        ButtonY_10_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_9->setFlat(true);
        ButtonY_10_10 = new QPushButton(page_2);
        ButtonY_10_10->setObjectName(QString::fromUtf8("ButtonY_10_10"));
        ButtonY_10_10->setGeometry(QRect(700, 518, 26, 26));
        ButtonY_10_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_10_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_10_10->setFlat(true);
        ButtonY_11_0 = new QPushButton(page_2);
        ButtonY_11_0->setObjectName(QString::fromUtf8("ButtonY_11_0"));
        ButtonY_11_0->setGeometry(QRect(353, 547, 26, 26));
        ButtonY_11_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_0->setFlat(true);
        ButtonY_11_1 = new QPushButton(page_2);
        ButtonY_11_1->setObjectName(QString::fromUtf8("ButtonY_11_1"));
        ButtonY_11_1->setGeometry(QRect(386, 547, 26, 26));
        ButtonY_11_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_1->setFlat(true);
        ButtonY_11_2 = new QPushButton(page_2);
        ButtonY_11_2->setObjectName(QString::fromUtf8("ButtonY_11_2"));
        ButtonY_11_2->setGeometry(QRect(419, 547, 26, 26));
        ButtonY_11_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_2->setFlat(true);
        ButtonY_11_3 = new QPushButton(page_2);
        ButtonY_11_3->setObjectName(QString::fromUtf8("ButtonY_11_3"));
        ButtonY_11_3->setGeometry(QRect(452, 547, 26, 26));
        ButtonY_11_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_3->setFlat(true);
        ButtonY_11_4 = new QPushButton(page_2);
        ButtonY_11_4->setObjectName(QString::fromUtf8("ButtonY_11_4"));
        ButtonY_11_4->setGeometry(QRect(485, 547, 26, 26));
        ButtonY_11_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_4->setFlat(true);
        ButtonY_11_5 = new QPushButton(page_2);
        ButtonY_11_5->setObjectName(QString::fromUtf8("ButtonY_11_5"));
        ButtonY_11_5->setGeometry(QRect(518, 547, 26, 26));
        ButtonY_11_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_5->setFlat(true);
        ButtonY_11_6 = new QPushButton(page_2);
        ButtonY_11_6->setObjectName(QString::fromUtf8("ButtonY_11_6"));
        ButtonY_11_6->setGeometry(QRect(551, 547, 26, 26));
        ButtonY_11_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_6->setFlat(true);
        ButtonY_11_7 = new QPushButton(page_2);
        ButtonY_11_7->setObjectName(QString::fromUtf8("ButtonY_11_7"));
        ButtonY_11_7->setGeometry(QRect(584, 547, 26, 26));
        ButtonY_11_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_7->setFlat(true);
        ButtonY_11_8 = new QPushButton(page_2);
        ButtonY_11_8->setObjectName(QString::fromUtf8("ButtonY_11_8"));
        ButtonY_11_8->setGeometry(QRect(617, 547, 26, 26));
        ButtonY_11_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_8->setFlat(true);
        ButtonY_11_9 = new QPushButton(page_2);
        ButtonY_11_9->setObjectName(QString::fromUtf8("ButtonY_11_9"));
        ButtonY_11_9->setGeometry(QRect(650, 547, 26, 26));
        ButtonY_11_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_9->setFlat(true);
        ButtonY_11_10 = new QPushButton(page_2);
        ButtonY_11_10->setObjectName(QString::fromUtf8("ButtonY_11_10"));
        ButtonY_11_10->setGeometry(QRect(683, 547, 26, 26));
        ButtonY_11_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_10->setFlat(true);
        ButtonY_11_11 = new QPushButton(page_2);
        ButtonY_11_11->setObjectName(QString::fromUtf8("ButtonY_11_11"));
        ButtonY_11_11->setGeometry(QRect(716, 547, 26, 26));
        ButtonY_11_11->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_11_11->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_11_11->setFlat(true);
        ButtonY_12_0 = new QPushButton(page_2);
        ButtonY_12_0->setObjectName(QString::fromUtf8("ButtonY_12_0"));
        ButtonY_12_0->setGeometry(QRect(336, 576, 26, 26));
        ButtonY_12_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_0->setFlat(true);
        ButtonY_12_1 = new QPushButton(page_2);
        ButtonY_12_1->setObjectName(QString::fromUtf8("ButtonY_12_1"));
        ButtonY_12_1->setGeometry(QRect(369, 576, 26, 26));
        ButtonY_12_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_1->setFlat(true);
        ButtonY_12_2 = new QPushButton(page_2);
        ButtonY_12_2->setObjectName(QString::fromUtf8("ButtonY_12_2"));
        ButtonY_12_2->setGeometry(QRect(402, 576, 26, 26));
        ButtonY_12_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_2->setFlat(true);
        ButtonY_12_3 = new QPushButton(page_2);
        ButtonY_12_3->setObjectName(QString::fromUtf8("ButtonY_12_3"));
        ButtonY_12_3->setGeometry(QRect(435, 576, 26, 26));
        ButtonY_12_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_3->setFlat(true);
        ButtonY_12_4 = new QPushButton(page_2);
        ButtonY_12_4->setObjectName(QString::fromUtf8("ButtonY_12_4"));
        ButtonY_12_4->setGeometry(QRect(468, 576, 26, 26));
        ButtonY_12_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_4->setFlat(true);
        ButtonY_12_5 = new QPushButton(page_2);
        ButtonY_12_5->setObjectName(QString::fromUtf8("ButtonY_12_5"));
        ButtonY_12_5->setGeometry(QRect(501, 576, 26, 26));
        ButtonY_12_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_5->setFlat(true);
        ButtonY_12_6 = new QPushButton(page_2);
        ButtonY_12_6->setObjectName(QString::fromUtf8("ButtonY_12_6"));
        ButtonY_12_6->setGeometry(QRect(534, 576, 26, 26));
        ButtonY_12_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_6->setFlat(true);
        ButtonY_12_7 = new QPushButton(page_2);
        ButtonY_12_7->setObjectName(QString::fromUtf8("ButtonY_12_7"));
        ButtonY_12_7->setGeometry(QRect(567, 576, 26, 26));
        ButtonY_12_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_7->setFlat(true);
        ButtonY_12_8 = new QPushButton(page_2);
        ButtonY_12_8->setObjectName(QString::fromUtf8("ButtonY_12_8"));
        ButtonY_12_8->setGeometry(QRect(600, 576, 26, 26));
        ButtonY_12_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_8->setFlat(true);
        ButtonY_12_9 = new QPushButton(page_2);
        ButtonY_12_9->setObjectName(QString::fromUtf8("ButtonY_12_9"));
        ButtonY_12_9->setGeometry(QRect(633, 576, 26, 26));
        ButtonY_12_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_9->setFlat(true);
        ButtonY_12_10 = new QPushButton(page_2);
        ButtonY_12_10->setObjectName(QString::fromUtf8("ButtonY_12_10"));
        ButtonY_12_10->setGeometry(QRect(666, 576, 26, 26));
        ButtonY_12_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_10->setFlat(true);
        ButtonY_12_11 = new QPushButton(page_2);
        ButtonY_12_11->setObjectName(QString::fromUtf8("ButtonY_12_11"));
        ButtonY_12_11->setGeometry(QRect(699, 576, 26, 26));
        ButtonY_12_11->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_11->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_11->setFlat(true);
        ButtonY_12_12 = new QPushButton(page_2);
        ButtonY_12_12->setObjectName(QString::fromUtf8("ButtonY_12_12"));
        ButtonY_12_12->setGeometry(QRect(732, 576, 26, 26));
        ButtonY_12_12->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_12_12->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_12_12->setFlat(true);
        ButtonY_13_0 = new QPushButton(page_2);
        ButtonY_13_0->setObjectName(QString::fromUtf8("ButtonY_13_0"));
        ButtonY_13_0->setGeometry(QRect(319, 605, 26, 26));
        ButtonY_13_0->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_0->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_0->setFlat(true);
        ButtonY_13_1 = new QPushButton(page_2);
        ButtonY_13_1->setObjectName(QString::fromUtf8("ButtonY_13_1"));
        ButtonY_13_1->setGeometry(QRect(352, 605, 26, 26));
        ButtonY_13_1->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_1->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_1->setFlat(true);
        ButtonY_13_2 = new QPushButton(page_2);
        ButtonY_13_2->setObjectName(QString::fromUtf8("ButtonY_13_2"));
        ButtonY_13_2->setGeometry(QRect(385, 605, 26, 26));
        ButtonY_13_2->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_2->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_2->setFlat(true);
        ButtonY_13_3 = new QPushButton(page_2);
        ButtonY_13_3->setObjectName(QString::fromUtf8("ButtonY_13_3"));
        ButtonY_13_3->setGeometry(QRect(418, 605, 26, 26));
        ButtonY_13_3->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_3->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_3->setFlat(true);
        ButtonY_13_4 = new QPushButton(page_2);
        ButtonY_13_4->setObjectName(QString::fromUtf8("ButtonY_13_4"));
        ButtonY_13_4->setGeometry(QRect(451, 605, 26, 26));
        ButtonY_13_4->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_4->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_4->setFlat(true);
        ButtonY_13_5 = new QPushButton(page_2);
        ButtonY_13_5->setObjectName(QString::fromUtf8("ButtonY_13_5"));
        ButtonY_13_5->setGeometry(QRect(484, 605, 26, 26));
        ButtonY_13_5->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_5->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_5->setFlat(true);
        ButtonY_13_6 = new QPushButton(page_2);
        ButtonY_13_6->setObjectName(QString::fromUtf8("ButtonY_13_6"));
        ButtonY_13_6->setGeometry(QRect(517, 605, 26, 26));
        ButtonY_13_6->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_6->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_6->setFlat(true);
        ButtonY_13_7 = new QPushButton(page_2);
        ButtonY_13_7->setObjectName(QString::fromUtf8("ButtonY_13_7"));
        ButtonY_13_7->setGeometry(QRect(550, 605, 26, 26));
        ButtonY_13_7->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_7->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_7->setFlat(true);
        ButtonY_13_8 = new QPushButton(page_2);
        ButtonY_13_8->setObjectName(QString::fromUtf8("ButtonY_13_8"));
        ButtonY_13_8->setGeometry(QRect(583, 605, 26, 26));
        ButtonY_13_8->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_8->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_8->setFlat(true);
        ButtonY_13_9 = new QPushButton(page_2);
        ButtonY_13_9->setObjectName(QString::fromUtf8("ButtonY_13_9"));
        ButtonY_13_9->setGeometry(QRect(616, 605, 26, 26));
        ButtonY_13_9->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_9->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_9->setFlat(true);
        ButtonY_13_10 = new QPushButton(page_2);
        ButtonY_13_10->setObjectName(QString::fromUtf8("ButtonY_13_10"));
        ButtonY_13_10->setGeometry(QRect(649, 605, 26, 26));
        ButtonY_13_10->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_10->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_10->setFlat(true);
        ButtonY_13_11 = new QPushButton(page_2);
        ButtonY_13_11->setObjectName(QString::fromUtf8("ButtonY_13_11"));
        ButtonY_13_11->setGeometry(QRect(682, 605, 26, 26));
        ButtonY_13_11->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_11->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_11->setFlat(true);
        ButtonY_13_12 = new QPushButton(page_2);
        ButtonY_13_12->setObjectName(QString::fromUtf8("ButtonY_13_12"));
        ButtonY_13_12->setGeometry(QRect(715, 605, 26, 26));
        ButtonY_13_12->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_12->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_12->setFlat(true);
        ButtonY_13_13 = new QPushButton(page_2);
        ButtonY_13_13->setObjectName(QString::fromUtf8("ButtonY_13_13"));
        ButtonY_13_13->setGeometry(QRect(748, 605, 26, 26));
        ButtonY_13_13->setCursor(QCursor(Qt::PointingHandCursor));
        ButtonY_13_13->setStyleSheet(QString::fromUtf8("border: none;"));
        ButtonY_13_13->setFlat(true);
        Patcher = new QPushButton(page_2);
        Patcher->setObjectName(QString::fromUtf8("Patcher"));
        Patcher->setGeometry(QRect(690, 50, 26, 26));
        Patcher->setCursor(QCursor(Qt::PointingHandCursor));
        Patcher->setStyleSheet(QString::fromUtf8("border: none;"));
        Patcher->setFlat(true);
        Turns = new QLabel(page_2);
        Turns->setObjectName(QString::fromUtf8("Turns"));
        Turns->setGeometry(QRect(250, 70, 611, 71));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Constantia"));
        font4.setPointSize(28);
        Turns->setFont(font4);
        Turns->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        IntrebareROP = new QLabel(page_3);
        IntrebareROP->setObjectName(QString::fromUtf8("IntrebareROP"));
        IntrebareROP->setGeometry(QRect(50, 200, 1041, 151));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Constantia"));
        font5.setPointSize(36);
        font5.setBold(true);
        font5.setWeight(75);
        IntrebareROP->setFont(font5);
        IntrebareROP->setAlignment(Qt::AlignCenter);
        DaRop = new QPushButton(page_3);
        DaRop->setObjectName(QString::fromUtf8("DaRop"));
        DaRop->setGeometry(QRect(240, 370, 231, 101));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Constantia"));
        font6.setPointSize(26);
        DaRop->setFont(font6);
        QIcon icon10;
        icon10.addFile(QString::fromUtf8("../GUI pictures/Da_Y.png"), QSize(), QIcon::Normal, QIcon::Off);
        DaRop->setIcon(icon10);
        DaRop->setIconSize(QSize(400, 250));
        DaRop->setFlat(true);
        NuROP = new QPushButton(page_3);
        NuROP->setObjectName(QString::fromUtf8("NuROP"));
        NuROP->setGeometry(QRect(600, 370, 231, 101));
        NuROP->setFont(font6);
        QIcon icon11;
        icon11.addFile(QString::fromUtf8("../GUI pictures/Nu_Y.png"), QSize(), QIcon::Normal, QIcon::Off);
        NuROP->setIcon(icon11);
        NuROP->setIconSize(QSize(400, 250));
        NuROP->setFlat(true);
        Winner = new QLabel(page_3);
        Winner->setObjectName(QString::fromUtf8("Winner"));
        Winner->setGeometry(QRect(90, 180, 961, 411));
        Winner->setFont(font5);
        Winner->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_3);
        Winner->raise();
        IntrebareROP->raise();
        DaRop->raise();
        NuROP->raise();

        retranslateUi(YUI);

        stackedWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(YUI);
    } // setupUi

    void retranslateUi(QFrame *YUI)
    {
        YUI->setWindowTitle(QCoreApplication::translate("YUI", "Y Game", nullptr));
        MesajEroare->setText(QString());
        pushButton->setText(QString());
        comboBox_P1->setItemText(0, QCoreApplication::translate("YUI", "Albastru", nullptr));
        comboBox_P1->setItemText(1, QCoreApplication::translate("YUI", "Verde", nullptr));
        comboBox_P1->setItemText(2, QCoreApplication::translate("YUI", "Negru", nullptr));
        comboBox_P1->setItemText(3, QCoreApplication::translate("YUI", "Galben", nullptr));
        comboBox_P1->setItemText(4, QCoreApplication::translate("YUI", "Portocaliu", nullptr));
        comboBox_P1->setItemText(5, QCoreApplication::translate("YUI", "Roz", nullptr));
        comboBox_P1->setItemText(6, QCoreApplication::translate("YUI", "Rosu", nullptr));
        comboBox_P1->setItemText(7, QCoreApplication::translate("YUI", "Mov", nullptr));

        CuloarePlayer1->setText(QCoreApplication::translate("YUI", "Alegeti culoarea primului jucator:", nullptr));
        NumePlayer1_2->setPlainText(QCoreApplication::translate("YUI", "Player1", nullptr));
        NumePlayer1->setText(QCoreApplication::translate("YUI", "Introduceti numele primului jucator:", nullptr));
        comboBox_P2->setItemText(0, QCoreApplication::translate("YUI", "Albastru", nullptr));
        comboBox_P2->setItemText(1, QCoreApplication::translate("YUI", "Verde", nullptr));
        comboBox_P2->setItemText(2, QCoreApplication::translate("YUI", "Negru", nullptr));
        comboBox_P2->setItemText(3, QCoreApplication::translate("YUI", "Galben", nullptr));
        comboBox_P2->setItemText(4, QCoreApplication::translate("YUI", "Portocaliu", nullptr));
        comboBox_P2->setItemText(5, QCoreApplication::translate("YUI", "Roz", nullptr));
        comboBox_P2->setItemText(6, QCoreApplication::translate("YUI", "Rosu", nullptr));
        comboBox_P2->setItemText(7, QCoreApplication::translate("YUI", "Mov", nullptr));

        NumePlayer2_2->setPlainText(QCoreApplication::translate("YUI", "Player2", nullptr));
        CuloarePlayer2->setText(QCoreApplication::translate("YUI", "Alegeti culoarea celui de-al doileai jucator:", nullptr));
        NumePlayer2->setText(QCoreApplication::translate("YUI", "Introduceti numele celui de-al doileai jucator:", nullptr));
        label->setText(QString());
        ButtonY_1_0->setText(QString());
        ButtonY_0_0->setText(QString());
        ButtonY_1_1->setText(QString());
        ButtonY_2_0->setText(QString());
        ButtonY_2_1->setText(QString());
        ButtonY_2_2->setText(QString());
        ButtonY_3_0->setText(QString());
        ButtonY_3_1->setText(QString());
        ButtonY_3_2->setText(QString());
        ButtonY_3_3->setText(QString());
        ButtonY_4_0->setText(QString());
        ButtonY_4_1->setText(QString());
        ButtonY_4_2->setText(QString());
        ButtonY_4_3->setText(QString());
        ButtonY_4_4->setText(QString());
        ButtonY_5_0->setText(QString());
        ButtonY_5_1->setText(QString());
        ButtonY_5_2->setText(QString());
        ButtonY_5_3->setText(QString());
        ButtonY_5_4->setText(QString());
        ButtonY_5_5->setText(QString());
        ButtonY_6_0->setText(QString());
        ButtonY_6_1->setText(QString());
        ButtonY_6_2->setText(QString());
        ButtonY_6_3->setText(QString());
        ButtonY_6_4->setText(QString());
        ButtonY_6_5->setText(QString());
        ButtonY_6_6->setText(QString());
        ButtonY_7_0->setText(QString());
        ButtonY_7_1->setText(QString());
        ButtonY_7_2->setText(QString());
        ButtonY_7_3->setText(QString());
        ButtonY_7_4->setText(QString());
        ButtonY_7_5->setText(QString());
        ButtonY_7_6->setText(QString());
        ButtonY_7_7->setText(QString());
        ButtonY_8_0->setText(QString());
        ButtonY_8_1->setText(QString());
        ButtonY_8_2->setText(QString());
        ButtonY_8_3->setText(QString());
        ButtonY_8_4->setText(QString());
        ButtonY_8_5->setText(QString());
        ButtonY_8_6->setText(QString());
        ButtonY_8_7->setText(QString());
        ButtonY_8_8->setText(QString());
        ButtonY_9_0->setText(QString());
        ButtonY_9_1->setText(QString());
        ButtonY_9_2->setText(QString());
        ButtonY_9_3->setText(QString());
        ButtonY_9_4->setText(QString());
        ButtonY_9_5->setText(QString());
        ButtonY_9_6->setText(QString());
        ButtonY_9_7->setText(QString());
        ButtonY_9_8->setText(QString());
        ButtonY_9_9->setText(QString());
        ButtonY_10_0->setText(QString());
        ButtonY_10_1->setText(QString());
        ButtonY_10_2->setText(QString());
        ButtonY_10_3->setText(QString());
        ButtonY_10_4->setText(QString());
        ButtonY_10_5->setText(QString());
        ButtonY_10_6->setText(QString());
        ButtonY_10_7->setText(QString());
        ButtonY_10_8->setText(QString());
        ButtonY_10_9->setText(QString());
        ButtonY_10_10->setText(QString());
        ButtonY_11_0->setText(QString());
        ButtonY_11_1->setText(QString());
        ButtonY_11_2->setText(QString());
        ButtonY_11_3->setText(QString());
        ButtonY_11_4->setText(QString());
        ButtonY_11_5->setText(QString());
        ButtonY_11_6->setText(QString());
        ButtonY_11_7->setText(QString());
        ButtonY_11_8->setText(QString());
        ButtonY_11_9->setText(QString());
        ButtonY_11_10->setText(QString());
        ButtonY_11_11->setText(QString());
        ButtonY_12_0->setText(QString());
        ButtonY_12_1->setText(QString());
        ButtonY_12_2->setText(QString());
        ButtonY_12_3->setText(QString());
        ButtonY_12_4->setText(QString());
        ButtonY_12_5->setText(QString());
        ButtonY_12_6->setText(QString());
        ButtonY_12_7->setText(QString());
        ButtonY_12_8->setText(QString());
        ButtonY_12_9->setText(QString());
        ButtonY_12_10->setText(QString());
        ButtonY_12_11->setText(QString());
        ButtonY_12_12->setText(QString());
        ButtonY_13_0->setText(QString());
        ButtonY_13_1->setText(QString());
        ButtonY_13_2->setText(QString());
        ButtonY_13_3->setText(QString());
        ButtonY_13_4->setText(QString());
        ButtonY_13_5->setText(QString());
        ButtonY_13_6->setText(QString());
        ButtonY_13_7->setText(QString());
        ButtonY_13_8->setText(QString());
        ButtonY_13_9->setText(QString());
        ButtonY_13_10->setText(QString());
        ButtonY_13_11->setText(QString());
        ButtonY_13_12->setText(QString());
        ButtonY_13_13->setText(QString());
        Patcher->setText(QString());
        Turns->setText(QString());
        IntrebareROP->setText(QCoreApplication::translate("YUI", "Doriti sa preluati miscarea primului jucator?", nullptr));
        DaRop->setText(QString());
        NuROP->setText(QString());
        Winner->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class YUI: public Ui_YUI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_YUI_H
